import { MigrationInterface, QueryRunner } from "typeorm";

export class Generate1753472764505 implements MigrationInterface {
    name = 'Generate1753472764505'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`folder\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`name\` varchar(255) NOT NULL, \`slug\` varchar(255) NOT NULL, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`organization_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`gallery\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`name\` varchar(255) NOT NULL, \`url\` varchar(255) NOT NULL, \`type\` varchar(255) NOT NULL, \`size\` varchar(255) NOT NULL, \`is_private\` tinyint NOT NULL DEFAULT 0, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`folder_id\` varchar(36) NULL, \`organization_id\` varchar(36) NULL, UNIQUE INDEX \`IDX_295fd6b6065fd46b418d79c6d0\` (\`url\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`role_action\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`read_only\` tinyint NOT NULL DEFAULT 0, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`action_id\` varchar(36) NOT NULL, \`role_id\` varchar(36) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`action\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`name\` varchar(255) NOT NULL, \`url\` varchar(255) NOT NULL, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`menu_id\` varchar(36) NULL, UNIQUE INDEX \`IDX_4aa35beeebe7073b51be93aae6\` (\`name\`), UNIQUE INDEX \`IDX_a37ba4bbcb187af36aa07b86c7\` (\`url\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_action\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`read_only\` tinyint NOT NULL DEFAULT 0, \`type\` enum ('1', '2', '3') NOT NULL DEFAULT '1', \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`action_id\` varchar(36) NOT NULL, \`user_id\` varchar(36) NOT NULL, \`organization_branch_id\` varchar(36) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_role\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`read_only\` tinyint NOT NULL DEFAULT 0, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`role_id\` varchar(36) NOT NULL, \`user_id\` varchar(36) NOT NULL, \`organization_branch_id\` varchar(36) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_organization\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`read_only\` tinyint NOT NULL DEFAULT 0, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`organization_id\` varchar(36) NOT NULL, \`user_id\` varchar(36) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_organization_branch\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`read_only\` tinyint NOT NULL DEFAULT 0, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`organization_id\` varchar(36) NOT NULL, \`user_id\` varchar(36) NOT NULL, \`organization_branch_id\` varchar(36) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NULL, \`phone\` varchar(255) NULL, \`password\` varchar(255) NULL, \`email\` varchar(255) NULL, \`user_generated_id\` varchar(255) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`profile_picture_id\` varchar(36) NULL, UNIQUE INDEX \`IDX_e12875dfb3b1d92d7d7c5377e2\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_menu\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`read_only\` tinyint NOT NULL DEFAULT 0, \`type\` enum ('1', '2', '3') NOT NULL DEFAULT '1', \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`menu_id\` varchar(36) NOT NULL, \`user_id\` varchar(36) NOT NULL, \`organization_branch_id\` varchar(36) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`menu\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`name\` varchar(255) NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`icon\` varchar(255) NULL, \`router_link\` varchar(255) NULL, \`serial\` int NULL, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`parent_id\` varchar(36) NULL, UNIQUE INDEX \`IDX_f37c203e9d061c884c4b034c83\` (\`name\`, \`parent_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`role_menu\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`read_only\` tinyint NOT NULL DEFAULT 0, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`menu_id\` varchar(36) NOT NULL, \`role_id\` varchar(36) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`role\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`name\` varchar(255) NOT NULL, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`organization_id\` varchar(36) NULL, UNIQUE INDEX \`IDX_ae4578dcaed5adff96595e6166\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`organization\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`read_only\` tinyint NOT NULL DEFAULT 0, \`name\` varchar(255) NOT NULL, \`slug\` varchar(255) NOT NULL, \`address\` longtext NULL, \`phone\` varchar(255) NULL, \`email\` varchar(255) NULL, \`serial\` int NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`image_id\` varchar(36) NULL, UNIQUE INDEX \`IDX_c21e615583a3ebbb0977452afb\` (\`name\`), UNIQUE INDEX \`IDX_a08804baa7c5d5427067c49a31\` (\`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`organization_branch\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`read_only\` tinyint NOT NULL DEFAULT 0, \`name\` varchar(255) NOT NULL, \`slug\` varchar(255) NOT NULL, \`address\` longtext NULL, \`phone\` varchar(255) NULL, \`email\` varchar(255) NULL, \`serial\` int NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`image_id\` varchar(36) NULL, \`parent_id\` varchar(36) NULL, \`organization_id\` varchar(36) NULL, UNIQUE INDEX \`IDX_7959957852249b5b6b58e0812b\` (\`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`otp_validation\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`client_request_id\` varchar(255) NOT NULL, \`value\` varchar(255) NOT NULL, \`code\` int NOT NULL, \`is_verified\` tinyint NOT NULL DEFAULT 0, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, UNIQUE INDEX \`IDX_64459517a9c0516dcfeb70fa7f\` (\`client_request_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_personal_info\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`father_name\` varchar(255) NULL, \`mother_name\` varchar(255) NULL, \`marital_status\` varchar(255) NULL, \`present_address\` text NULL, \`permanent_address\` text NULL, \`profession\` varchar(255) NULL, \`nominee_name\` varchar(255) NULL, \`relation_with_nominee\` varchar(255) NULL, \`comments\` text NULL, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`user_id\` varchar(36) NOT NULL, \`nid_photo_id\` varchar(36) NULL, \`nominee_nid_photo_id\` varchar(36) NULL, \`refer_user_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`expense\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`title\` varchar(200) NOT NULL, \`description\` text NULL, \`amount\` decimal(12,2) NOT NULL, \`type\` enum ('fixed', 'variable', 'one_time') NOT NULL DEFAULT 'variable', \`date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`recorded_by\` varchar(36) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cash\` (\`id\` varchar(36) NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`date\` date NOT NULL, \`amount\` decimal(12,2) NOT NULL, \`type\` enum ('credit', 'debit') NOT NULL, \`note\` text NULL, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`cash_by\` varchar(36) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`folder\` ADD CONSTRAINT \`FK_afa55bd45385d7731c51de3eba3\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`folder\` ADD CONSTRAINT \`FK_ae991a4ac1bad2af0c06be6c560\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`folder\` ADD CONSTRAINT \`FK_82a84faa50e26fca20759bb3c24\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`folder\` ADD CONSTRAINT \`FK_fd89c6b76b9f8bdd18c3b8aa30a\` FOREIGN KEY (\`organization_id\`) REFERENCES \`organization\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`gallery\` ADD CONSTRAINT \`FK_0f74efc873fee52182bb4901e54\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`gallery\` ADD CONSTRAINT \`FK_73247f9d2e296742ae2e1b86980\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`gallery\` ADD CONSTRAINT \`FK_2254620b97af3786723cd5a8162\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`gallery\` ADD CONSTRAINT \`FK_6048ebaa4100a5d6d874468602d\` FOREIGN KEY (\`folder_id\`) REFERENCES \`folder\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`gallery\` ADD CONSTRAINT \`FK_6269b22b557dce812c46006fc5c\` FOREIGN KEY (\`organization_id\`) REFERENCES \`organization\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_action\` ADD CONSTRAINT \`FK_35a27e861035e06f9b61d7a4d62\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_action\` ADD CONSTRAINT \`FK_f2b0ba1d72861fd9a02af3d96d2\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_action\` ADD CONSTRAINT \`FK_4e6b4180589bf1e10f8e436f3f5\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_action\` ADD CONSTRAINT \`FK_db06d82a57d7c9fb7dd36f5a631\` FOREIGN KEY (\`action_id\`) REFERENCES \`action\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_action\` ADD CONSTRAINT \`FK_f39cfd766e4b1a93e105c2fd675\` FOREIGN KEY (\`role_id\`) REFERENCES \`role\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`action\` ADD CONSTRAINT \`FK_513f1e020ad5ceafb38243fcc99\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`action\` ADD CONSTRAINT \`FK_fb357193ebb00db91b6c661e466\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`action\` ADD CONSTRAINT \`FK_d82f3c20a5a0ffd620f54e52d89\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`action\` ADD CONSTRAINT \`FK_6ffa6956165e8a372a397036544\` FOREIGN KEY (\`menu_id\`) REFERENCES \`menu\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_action\` ADD CONSTRAINT \`FK_2f2800a926203df078ed99618ee\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_action\` ADD CONSTRAINT \`FK_bdec1f05527c3a86a3a33cdaf45\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_action\` ADD CONSTRAINT \`FK_b37e2072f24b5246c50fb883a8f\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_action\` ADD CONSTRAINT \`FK_a3297a84ad4aba5b83152ac4273\` FOREIGN KEY (\`action_id\`) REFERENCES \`action\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_action\` ADD CONSTRAINT \`FK_baabb9b6ff427e792ad1f8558b1\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_action\` ADD CONSTRAINT \`FK_7ed031a32e5a53a0edcd8a355b7\` FOREIGN KEY (\`organization_branch_id\`) REFERENCES \`organization_branch\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_role\` ADD CONSTRAINT \`FK_0d65d1750949a41a47c174ed36a\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_role\` ADD CONSTRAINT \`FK_601092acc2e4c5bf3beb59de552\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_role\` ADD CONSTRAINT \`FK_d86c34a7d3f4de13a376d859b1f\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_role\` ADD CONSTRAINT \`FK_32a6fc2fcb019d8e3a8ace0f55f\` FOREIGN KEY (\`role_id\`) REFERENCES \`role\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_role\` ADD CONSTRAINT \`FK_d0e5815877f7395a198a4cb0a46\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_role\` ADD CONSTRAINT \`FK_4c116d7f899a0e5eec667f68b43\` FOREIGN KEY (\`organization_branch_id\`) REFERENCES \`organization_branch\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_organization\` ADD CONSTRAINT \`FK_3f5fe8d482f503e4bdd58ae4a35\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_organization\` ADD CONSTRAINT \`FK_00de586414f24a62bcbfbd3e828\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_organization\` ADD CONSTRAINT \`FK_0ea503d79b8738cf164d90b5066\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_organization\` ADD CONSTRAINT \`FK_f2d20e8f038adda18639b2db1b8\` FOREIGN KEY (\`organization_id\`) REFERENCES \`organization\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_organization\` ADD CONSTRAINT \`FK_3380ac618acf226e1c2d6e9a228\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_organization_branch\` ADD CONSTRAINT \`FK_23a9b35414aa5646ed415a9724f\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_organization_branch\` ADD CONSTRAINT \`FK_3df6f720f67130e43d639714242\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_organization_branch\` ADD CONSTRAINT \`FK_c749ec6544fa35350812dd8e962\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_organization_branch\` ADD CONSTRAINT \`FK_8b1a0e1caa41ef7b887208b8d83\` FOREIGN KEY (\`organization_id\`) REFERENCES \`organization\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_organization_branch\` ADD CONSTRAINT \`FK_5f70424c18736377ec7e16f50ea\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_organization_branch\` ADD CONSTRAINT \`FK_1ddca600f70950df6ea3445c7e8\` FOREIGN KEY (\`organization_branch_id\`) REFERENCES \`organization_branch\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD CONSTRAINT \`FK_e4238c3828bc51ff8ca27c46385\` FOREIGN KEY (\`profile_picture_id\`) REFERENCES \`gallery\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_menu\` ADD CONSTRAINT \`FK_711340d011c34d1e3681b7b7246\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_menu\` ADD CONSTRAINT \`FK_0ce306fa523198d3a21893be3dc\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_menu\` ADD CONSTRAINT \`FK_19c71475c41bef04813e155f4dc\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_menu\` ADD CONSTRAINT \`FK_c22cdf874bcc1756774e746cf21\` FOREIGN KEY (\`menu_id\`) REFERENCES \`menu\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_menu\` ADD CONSTRAINT \`FK_2b894f35bf611630a8f5de5b40e\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_menu\` ADD CONSTRAINT \`FK_1a22316f0ae6cbd7327ed55d619\` FOREIGN KEY (\`organization_branch_id\`) REFERENCES \`organization_branch\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`menu\` ADD CONSTRAINT \`FK_592f239d67fb01e3db306325de5\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`menu\` ADD CONSTRAINT \`FK_07c2fb7633405194486e0ffc1ac\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`menu\` ADD CONSTRAINT \`FK_3480ccb9d92107de249e8e687d3\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`menu\` ADD CONSTRAINT \`FK_e5e28130fd17f88ab5ee5d3aa4c\` FOREIGN KEY (\`parent_id\`) REFERENCES \`menu\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_menu\` ADD CONSTRAINT \`FK_0d50a43e3f8b59beee01da60426\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_menu\` ADD CONSTRAINT \`FK_d603d1aed76afe4f977f84e490e\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_menu\` ADD CONSTRAINT \`FK_67d83c6982183a7ab4edad562eb\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_menu\` ADD CONSTRAINT \`FK_96d26921e6aa2172256a55a6bc7\` FOREIGN KEY (\`menu_id\`) REFERENCES \`menu\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_menu\` ADD CONSTRAINT \`FK_25f45e543fbda0c91da4af7a2a9\` FOREIGN KEY (\`role_id\`) REFERENCES \`role\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role\` ADD CONSTRAINT \`FK_04a09925beea59e864e921db4a1\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role\` ADD CONSTRAINT \`FK_858c871a036f61e56e2740c7cda\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role\` ADD CONSTRAINT \`FK_7b5b6fdd043b90e1d461b4b681d\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role\` ADD CONSTRAINT \`FK_2c1fc97f79b82800ef15372b98c\` FOREIGN KEY (\`organization_id\`) REFERENCES \`organization\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organization\` ADD CONSTRAINT \`FK_d348286667373cbcec5463cda5b\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organization\` ADD CONSTRAINT \`FK_b0c596f429ff2966d03516ef1ca\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organization\` ADD CONSTRAINT \`FK_edd3d199e09845da9c76636170a\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organization\` ADD CONSTRAINT \`FK_09e72692b015f30ba80789b3523\` FOREIGN KEY (\`image_id\`) REFERENCES \`gallery\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` ADD CONSTRAINT \`FK_334b3da6f12f406e929410bde33\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` ADD CONSTRAINT \`FK_5cbb84c0b66cf3351c388a3befd\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` ADD CONSTRAINT \`FK_e5f30f8b681a9589798d92d7d97\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` ADD CONSTRAINT \`FK_730c23f8bd493d0146d2bcf16b0\` FOREIGN KEY (\`image_id\`) REFERENCES \`gallery\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` ADD CONSTRAINT \`FK_95c4aa165f12726c58b02de0528\` FOREIGN KEY (\`parent_id\`) REFERENCES \`organization_branch\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` ADD CONSTRAINT \`FK_7d3afd6e0258e5483beaee5f652\` FOREIGN KEY (\`organization_id\`) REFERENCES \`organization\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`otp_validation\` ADD CONSTRAINT \`FK_c4481f02e27bd69089089d34ef7\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`otp_validation\` ADD CONSTRAINT \`FK_edfa210813fa9a16cfb2164584d\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`otp_validation\` ADD CONSTRAINT \`FK_d94f16071e43d84299dea42720c\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` ADD CONSTRAINT \`FK_caa41b91f3c30a0f0a172187d9d\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` ADD CONSTRAINT \`FK_331edc6c04733098c74e3b39f81\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` ADD CONSTRAINT \`FK_316d2ef1146129a4d233863f823\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` ADD CONSTRAINT \`FK_26f4189498c6b038bfc624953c2\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` ADD CONSTRAINT \`FK_d39fdb10b9b1371666605df2a35\` FOREIGN KEY (\`nid_photo_id\`) REFERENCES \`gallery\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` ADD CONSTRAINT \`FK_961f12b246483a48d837dbbd557\` FOREIGN KEY (\`nominee_nid_photo_id\`) REFERENCES \`gallery\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` ADD CONSTRAINT \`FK_a23f383a4aaf0f6ec1c3ff64fe8\` FOREIGN KEY (\`refer_user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`expense\` ADD CONSTRAINT \`FK_d7f0f7ca79854cf3b8a6eb0265f\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`expense\` ADD CONSTRAINT \`FK_e03ae853c8541a99221514c8ae7\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`expense\` ADD CONSTRAINT \`FK_76027b498dcb26ee7074c6858dc\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`expense\` ADD CONSTRAINT \`FK_249ef73eec456a37c899e369941\` FOREIGN KEY (\`recorded_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cash\` ADD CONSTRAINT \`FK_8f84d7e2fe678cfe0698d5c6c7a\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cash\` ADD CONSTRAINT \`FK_51811f839b26b081efe01f0935f\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cash\` ADD CONSTRAINT \`FK_7563aade7bf3f1fd27584ea620b\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cash\` ADD CONSTRAINT \`FK_badc477ee8c7f60784ffced5ccb\` FOREIGN KEY (\`cash_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`cash\` DROP FOREIGN KEY \`FK_badc477ee8c7f60784ffced5ccb\``);
        await queryRunner.query(`ALTER TABLE \`cash\` DROP FOREIGN KEY \`FK_7563aade7bf3f1fd27584ea620b\``);
        await queryRunner.query(`ALTER TABLE \`cash\` DROP FOREIGN KEY \`FK_51811f839b26b081efe01f0935f\``);
        await queryRunner.query(`ALTER TABLE \`cash\` DROP FOREIGN KEY \`FK_8f84d7e2fe678cfe0698d5c6c7a\``);
        await queryRunner.query(`ALTER TABLE \`expense\` DROP FOREIGN KEY \`FK_249ef73eec456a37c899e369941\``);
        await queryRunner.query(`ALTER TABLE \`expense\` DROP FOREIGN KEY \`FK_76027b498dcb26ee7074c6858dc\``);
        await queryRunner.query(`ALTER TABLE \`expense\` DROP FOREIGN KEY \`FK_e03ae853c8541a99221514c8ae7\``);
        await queryRunner.query(`ALTER TABLE \`expense\` DROP FOREIGN KEY \`FK_d7f0f7ca79854cf3b8a6eb0265f\``);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` DROP FOREIGN KEY \`FK_a23f383a4aaf0f6ec1c3ff64fe8\``);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` DROP FOREIGN KEY \`FK_961f12b246483a48d837dbbd557\``);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` DROP FOREIGN KEY \`FK_d39fdb10b9b1371666605df2a35\``);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` DROP FOREIGN KEY \`FK_26f4189498c6b038bfc624953c2\``);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` DROP FOREIGN KEY \`FK_316d2ef1146129a4d233863f823\``);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` DROP FOREIGN KEY \`FK_331edc6c04733098c74e3b39f81\``);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` DROP FOREIGN KEY \`FK_caa41b91f3c30a0f0a172187d9d\``);
        await queryRunner.query(`ALTER TABLE \`otp_validation\` DROP FOREIGN KEY \`FK_d94f16071e43d84299dea42720c\``);
        await queryRunner.query(`ALTER TABLE \`otp_validation\` DROP FOREIGN KEY \`FK_edfa210813fa9a16cfb2164584d\``);
        await queryRunner.query(`ALTER TABLE \`otp_validation\` DROP FOREIGN KEY \`FK_c4481f02e27bd69089089d34ef7\``);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` DROP FOREIGN KEY \`FK_7d3afd6e0258e5483beaee5f652\``);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` DROP FOREIGN KEY \`FK_95c4aa165f12726c58b02de0528\``);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` DROP FOREIGN KEY \`FK_730c23f8bd493d0146d2bcf16b0\``);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` DROP FOREIGN KEY \`FK_e5f30f8b681a9589798d92d7d97\``);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` DROP FOREIGN KEY \`FK_5cbb84c0b66cf3351c388a3befd\``);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` DROP FOREIGN KEY \`FK_334b3da6f12f406e929410bde33\``);
        await queryRunner.query(`ALTER TABLE \`organization\` DROP FOREIGN KEY \`FK_09e72692b015f30ba80789b3523\``);
        await queryRunner.query(`ALTER TABLE \`organization\` DROP FOREIGN KEY \`FK_edd3d199e09845da9c76636170a\``);
        await queryRunner.query(`ALTER TABLE \`organization\` DROP FOREIGN KEY \`FK_b0c596f429ff2966d03516ef1ca\``);
        await queryRunner.query(`ALTER TABLE \`organization\` DROP FOREIGN KEY \`FK_d348286667373cbcec5463cda5b\``);
        await queryRunner.query(`ALTER TABLE \`role\` DROP FOREIGN KEY \`FK_2c1fc97f79b82800ef15372b98c\``);
        await queryRunner.query(`ALTER TABLE \`role\` DROP FOREIGN KEY \`FK_7b5b6fdd043b90e1d461b4b681d\``);
        await queryRunner.query(`ALTER TABLE \`role\` DROP FOREIGN KEY \`FK_858c871a036f61e56e2740c7cda\``);
        await queryRunner.query(`ALTER TABLE \`role\` DROP FOREIGN KEY \`FK_04a09925beea59e864e921db4a1\``);
        await queryRunner.query(`ALTER TABLE \`role_menu\` DROP FOREIGN KEY \`FK_25f45e543fbda0c91da4af7a2a9\``);
        await queryRunner.query(`ALTER TABLE \`role_menu\` DROP FOREIGN KEY \`FK_96d26921e6aa2172256a55a6bc7\``);
        await queryRunner.query(`ALTER TABLE \`role_menu\` DROP FOREIGN KEY \`FK_67d83c6982183a7ab4edad562eb\``);
        await queryRunner.query(`ALTER TABLE \`role_menu\` DROP FOREIGN KEY \`FK_d603d1aed76afe4f977f84e490e\``);
        await queryRunner.query(`ALTER TABLE \`role_menu\` DROP FOREIGN KEY \`FK_0d50a43e3f8b59beee01da60426\``);
        await queryRunner.query(`ALTER TABLE \`menu\` DROP FOREIGN KEY \`FK_e5e28130fd17f88ab5ee5d3aa4c\``);
        await queryRunner.query(`ALTER TABLE \`menu\` DROP FOREIGN KEY \`FK_3480ccb9d92107de249e8e687d3\``);
        await queryRunner.query(`ALTER TABLE \`menu\` DROP FOREIGN KEY \`FK_07c2fb7633405194486e0ffc1ac\``);
        await queryRunner.query(`ALTER TABLE \`menu\` DROP FOREIGN KEY \`FK_592f239d67fb01e3db306325de5\``);
        await queryRunner.query(`ALTER TABLE \`user_menu\` DROP FOREIGN KEY \`FK_1a22316f0ae6cbd7327ed55d619\``);
        await queryRunner.query(`ALTER TABLE \`user_menu\` DROP FOREIGN KEY \`FK_2b894f35bf611630a8f5de5b40e\``);
        await queryRunner.query(`ALTER TABLE \`user_menu\` DROP FOREIGN KEY \`FK_c22cdf874bcc1756774e746cf21\``);
        await queryRunner.query(`ALTER TABLE \`user_menu\` DROP FOREIGN KEY \`FK_19c71475c41bef04813e155f4dc\``);
        await queryRunner.query(`ALTER TABLE \`user_menu\` DROP FOREIGN KEY \`FK_0ce306fa523198d3a21893be3dc\``);
        await queryRunner.query(`ALTER TABLE \`user_menu\` DROP FOREIGN KEY \`FK_711340d011c34d1e3681b7b7246\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP FOREIGN KEY \`FK_e4238c3828bc51ff8ca27c46385\``);
        await queryRunner.query(`ALTER TABLE \`user_organization_branch\` DROP FOREIGN KEY \`FK_1ddca600f70950df6ea3445c7e8\``);
        await queryRunner.query(`ALTER TABLE \`user_organization_branch\` DROP FOREIGN KEY \`FK_5f70424c18736377ec7e16f50ea\``);
        await queryRunner.query(`ALTER TABLE \`user_organization_branch\` DROP FOREIGN KEY \`FK_8b1a0e1caa41ef7b887208b8d83\``);
        await queryRunner.query(`ALTER TABLE \`user_organization_branch\` DROP FOREIGN KEY \`FK_c749ec6544fa35350812dd8e962\``);
        await queryRunner.query(`ALTER TABLE \`user_organization_branch\` DROP FOREIGN KEY \`FK_3df6f720f67130e43d639714242\``);
        await queryRunner.query(`ALTER TABLE \`user_organization_branch\` DROP FOREIGN KEY \`FK_23a9b35414aa5646ed415a9724f\``);
        await queryRunner.query(`ALTER TABLE \`user_organization\` DROP FOREIGN KEY \`FK_3380ac618acf226e1c2d6e9a228\``);
        await queryRunner.query(`ALTER TABLE \`user_organization\` DROP FOREIGN KEY \`FK_f2d20e8f038adda18639b2db1b8\``);
        await queryRunner.query(`ALTER TABLE \`user_organization\` DROP FOREIGN KEY \`FK_0ea503d79b8738cf164d90b5066\``);
        await queryRunner.query(`ALTER TABLE \`user_organization\` DROP FOREIGN KEY \`FK_00de586414f24a62bcbfbd3e828\``);
        await queryRunner.query(`ALTER TABLE \`user_organization\` DROP FOREIGN KEY \`FK_3f5fe8d482f503e4bdd58ae4a35\``);
        await queryRunner.query(`ALTER TABLE \`user_role\` DROP FOREIGN KEY \`FK_4c116d7f899a0e5eec667f68b43\``);
        await queryRunner.query(`ALTER TABLE \`user_role\` DROP FOREIGN KEY \`FK_d0e5815877f7395a198a4cb0a46\``);
        await queryRunner.query(`ALTER TABLE \`user_role\` DROP FOREIGN KEY \`FK_32a6fc2fcb019d8e3a8ace0f55f\``);
        await queryRunner.query(`ALTER TABLE \`user_role\` DROP FOREIGN KEY \`FK_d86c34a7d3f4de13a376d859b1f\``);
        await queryRunner.query(`ALTER TABLE \`user_role\` DROP FOREIGN KEY \`FK_601092acc2e4c5bf3beb59de552\``);
        await queryRunner.query(`ALTER TABLE \`user_role\` DROP FOREIGN KEY \`FK_0d65d1750949a41a47c174ed36a\``);
        await queryRunner.query(`ALTER TABLE \`user_action\` DROP FOREIGN KEY \`FK_7ed031a32e5a53a0edcd8a355b7\``);
        await queryRunner.query(`ALTER TABLE \`user_action\` DROP FOREIGN KEY \`FK_baabb9b6ff427e792ad1f8558b1\``);
        await queryRunner.query(`ALTER TABLE \`user_action\` DROP FOREIGN KEY \`FK_a3297a84ad4aba5b83152ac4273\``);
        await queryRunner.query(`ALTER TABLE \`user_action\` DROP FOREIGN KEY \`FK_b37e2072f24b5246c50fb883a8f\``);
        await queryRunner.query(`ALTER TABLE \`user_action\` DROP FOREIGN KEY \`FK_bdec1f05527c3a86a3a33cdaf45\``);
        await queryRunner.query(`ALTER TABLE \`user_action\` DROP FOREIGN KEY \`FK_2f2800a926203df078ed99618ee\``);
        await queryRunner.query(`ALTER TABLE \`action\` DROP FOREIGN KEY \`FK_6ffa6956165e8a372a397036544\``);
        await queryRunner.query(`ALTER TABLE \`action\` DROP FOREIGN KEY \`FK_d82f3c20a5a0ffd620f54e52d89\``);
        await queryRunner.query(`ALTER TABLE \`action\` DROP FOREIGN KEY \`FK_fb357193ebb00db91b6c661e466\``);
        await queryRunner.query(`ALTER TABLE \`action\` DROP FOREIGN KEY \`FK_513f1e020ad5ceafb38243fcc99\``);
        await queryRunner.query(`ALTER TABLE \`role_action\` DROP FOREIGN KEY \`FK_f39cfd766e4b1a93e105c2fd675\``);
        await queryRunner.query(`ALTER TABLE \`role_action\` DROP FOREIGN KEY \`FK_db06d82a57d7c9fb7dd36f5a631\``);
        await queryRunner.query(`ALTER TABLE \`role_action\` DROP FOREIGN KEY \`FK_4e6b4180589bf1e10f8e436f3f5\``);
        await queryRunner.query(`ALTER TABLE \`role_action\` DROP FOREIGN KEY \`FK_f2b0ba1d72861fd9a02af3d96d2\``);
        await queryRunner.query(`ALTER TABLE \`role_action\` DROP FOREIGN KEY \`FK_35a27e861035e06f9b61d7a4d62\``);
        await queryRunner.query(`ALTER TABLE \`gallery\` DROP FOREIGN KEY \`FK_6269b22b557dce812c46006fc5c\``);
        await queryRunner.query(`ALTER TABLE \`gallery\` DROP FOREIGN KEY \`FK_6048ebaa4100a5d6d874468602d\``);
        await queryRunner.query(`ALTER TABLE \`gallery\` DROP FOREIGN KEY \`FK_2254620b97af3786723cd5a8162\``);
        await queryRunner.query(`ALTER TABLE \`gallery\` DROP FOREIGN KEY \`FK_73247f9d2e296742ae2e1b86980\``);
        await queryRunner.query(`ALTER TABLE \`gallery\` DROP FOREIGN KEY \`FK_0f74efc873fee52182bb4901e54\``);
        await queryRunner.query(`ALTER TABLE \`folder\` DROP FOREIGN KEY \`FK_fd89c6b76b9f8bdd18c3b8aa30a\``);
        await queryRunner.query(`ALTER TABLE \`folder\` DROP FOREIGN KEY \`FK_82a84faa50e26fca20759bb3c24\``);
        await queryRunner.query(`ALTER TABLE \`folder\` DROP FOREIGN KEY \`FK_ae991a4ac1bad2af0c06be6c560\``);
        await queryRunner.query(`ALTER TABLE \`folder\` DROP FOREIGN KEY \`FK_afa55bd45385d7731c51de3eba3\``);
        await queryRunner.query(`DROP TABLE \`cash\``);
        await queryRunner.query(`DROP TABLE \`expense\``);
        await queryRunner.query(`DROP TABLE \`user_personal_info\``);
        await queryRunner.query(`DROP INDEX \`IDX_64459517a9c0516dcfeb70fa7f\` ON \`otp_validation\``);
        await queryRunner.query(`DROP TABLE \`otp_validation\``);
        await queryRunner.query(`DROP INDEX \`IDX_7959957852249b5b6b58e0812b\` ON \`organization_branch\``);
        await queryRunner.query(`DROP TABLE \`organization_branch\``);
        await queryRunner.query(`DROP INDEX \`IDX_a08804baa7c5d5427067c49a31\` ON \`organization\``);
        await queryRunner.query(`DROP INDEX \`IDX_c21e615583a3ebbb0977452afb\` ON \`organization\``);
        await queryRunner.query(`DROP TABLE \`organization\``);
        await queryRunner.query(`DROP INDEX \`IDX_ae4578dcaed5adff96595e6166\` ON \`role\``);
        await queryRunner.query(`DROP TABLE \`role\``);
        await queryRunner.query(`DROP TABLE \`role_menu\``);
        await queryRunner.query(`DROP INDEX \`IDX_f37c203e9d061c884c4b034c83\` ON \`menu\``);
        await queryRunner.query(`DROP TABLE \`menu\``);
        await queryRunner.query(`DROP TABLE \`user_menu\``);
        await queryRunner.query(`DROP INDEX \`IDX_e12875dfb3b1d92d7d7c5377e2\` ON \`user\``);
        await queryRunner.query(`DROP TABLE \`user\``);
        await queryRunner.query(`DROP TABLE \`user_organization_branch\``);
        await queryRunner.query(`DROP TABLE \`user_organization\``);
        await queryRunner.query(`DROP TABLE \`user_role\``);
        await queryRunner.query(`DROP TABLE \`user_action\``);
        await queryRunner.query(`DROP INDEX \`IDX_a37ba4bbcb187af36aa07b86c7\` ON \`action\``);
        await queryRunner.query(`DROP INDEX \`IDX_4aa35beeebe7073b51be93aae6\` ON \`action\``);
        await queryRunner.query(`DROP TABLE \`action\``);
        await queryRunner.query(`DROP TABLE \`role_action\``);
        await queryRunner.query(`DROP INDEX \`IDX_295fd6b6065fd46b418d79c6d0\` ON \`gallery\``);
        await queryRunner.query(`DROP TABLE \`gallery\``);
        await queryRunner.query(`DROP TABLE \`folder\``);
    }

}
