import { MigrationInterface, QueryRunner } from "typeorm";

export class Generate1758627758504 implements MigrationInterface {
    name = 'Generate1758627758504'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`folder\` (\`id\` varchar(36) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`name\` varchar(255) NOT NULL, \`slug\` varchar(255) NOT NULL, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`organization_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`gallery\` (\`id\` varchar(36) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`name\` varchar(255) NOT NULL, \`url\` varchar(500) NOT NULL, \`type\` varchar(255) NOT NULL, \`size\` varchar(255) NOT NULL, \`is_private\` tinyint NOT NULL DEFAULT 0, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`folder_id\` varchar(36) NULL, \`organization_id\` varchar(36) NULL, UNIQUE INDEX \`IDX_295fd6b6065fd46b418d79c6d0\` (\`url\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`role\` (\`id\` varchar(36) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`name\` varchar(255) NOT NULL, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`organization_id\` varchar(36) NULL, UNIQUE INDEX \`IDX_ae4578dcaed5adff96595e6166\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`organization\` (\`id\` varchar(36) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`read_only\` tinyint NOT NULL DEFAULT 0, \`name\` varchar(255) NOT NULL, \`slug\` varchar(255) NOT NULL, \`address\` longtext NULL, \`phone\` varchar(50) NULL, \`email\` varchar(255) NULL, \`serial\` int NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`additional_fields\` json NULL, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`image_id\` varchar(36) NULL, UNIQUE INDEX \`IDX_c21e615583a3ebbb0977452afb\` (\`name\`), UNIQUE INDEX \`IDX_a08804baa7c5d5427067c49a31\` (\`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`organization_branch\` (\`id\` varchar(36) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`read_only\` tinyint NOT NULL DEFAULT 0, \`name\` varchar(255) NOT NULL, \`slug\` varchar(255) NOT NULL, \`address\` longtext NULL, \`phone\` varchar(50) NULL, \`email\` varchar(255) NULL, \`serial\` int NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`image_id\` varchar(36) NULL, \`parent_id\` varchar(36) NULL, \`organization_id\` varchar(36) NULL, UNIQUE INDEX \`IDX_155ab20d89516db9cb05031f4f\` (\`organization_id\`, \`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`permission_history\` (\`id\` int NOT NULL AUTO_INCREMENT, \`permission_id\` varchar(255) NOT NULL, \`subject_type\` varchar(100) NOT NULL, \`subject_id\` varchar(255) NOT NULL, \`scope_type\` varchar(100) NOT NULL, \`scope_id\` varchar(255) NOT NULL, \`action\` varchar(10) NOT NULL, \`previous_value\` json NULL, \`new_value\` json NULL, \`timestamp\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`performed_by\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`permission\` (\`id\` varchar(36) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`subject_type\` varchar(100) NOT NULL, \`subject_id\` varchar(255) NOT NULL, \`scope_type\` varchar(100) NOT NULL, \`scope_id\` varchar(255) NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`type\` int NULL, \`organization_branch_id\` varchar(255) NULL, \`organization_id\` varchar(255) NULL, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`menu\` (\`id\` varchar(36) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`groups\` text NOT NULL, \`name\` varchar(255) NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`icon_type\` int NOT NULL DEFAULT '1', \`icon\` varchar(255) NULL, \`router_link\` varchar(255) NULL, \`serial\` int NULL, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`parent_id\` varchar(36) NULL, UNIQUE INDEX \`IDX_f37c203e9d061c884c4b034c83\` (\`name\`, \`parent_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`action\` (\`id\` varchar(36) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`groups\` text NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`name\` varchar(255) NOT NULL, \`url\` varchar(255) NOT NULL, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`menu_id\` varchar(36) NULL, UNIQUE INDEX \`IDX_4aa35beeebe7073b51be93aae6\` (\`name\`), UNIQUE INDEX \`IDX_a37ba4bbcb187af36aa07b86c7\` (\`url\`), UNIQUE INDEX \`IDX_e3f27529ac3d5b49ce85938917\` (\`url\`, \`menu_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`app\` (\`id\` varchar(36) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`name\` varchar(255) NOT NULL, \`slug\` varchar(255) NOT NULL, \`icon_type\` int NOT NULL DEFAULT '1', \`icon\` varchar(255) NULL, \`is_external\` tinyint NOT NULL DEFAULT 0, \`external_link\` varchar(255) NULL, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, UNIQUE INDEX \`IDX_f36adbb7b096ceeb6f3e80ad14\` (\`name\`), UNIQUE INDEX \`IDX_8993112cd607f65268a4f57da3\` (\`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`otp_validation\` (\`id\` varchar(36) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`client_request_id\` varchar(255) NOT NULL, \`value\` varchar(50) NOT NULL, \`code\` int NOT NULL, \`is_verified\` tinyint NOT NULL DEFAULT 0, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, UNIQUE INDEX \`IDX_64459517a9c0516dcfeb70fa7f\` (\`client_request_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NULL, \`phone\` varchar(255) NULL, \`password\` text NULL, \`email\` varchar(255) NOT NULL, \`user_generated_id\` varchar(255) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`profile_picture_id\` varchar(36) NULL, UNIQUE INDEX \`IDX_e12875dfb3b1d92d7d7c5377e2\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_personal_info\` (\`id\` varchar(36) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`father_name\` varchar(255) NULL, \`mother_name\` varchar(255) NULL, \`marital_status\` varchar(255) NULL, \`present_address\` text NULL, \`permanent_address\` text NULL, \`profession\` varchar(255) NULL, \`nominee_name\` varchar(255) NULL, \`relation_with_nominee\` varchar(255) NULL, \`comments\` text NULL, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`user_id\` varchar(36) NOT NULL, \`nid_photo_id\` varchar(36) NULL, \`nominee_nid_photo_id\` varchar(36) NULL, \`refer_user_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`expense\` (\`id\` varchar(36) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`title\` varchar(200) NOT NULL, \`description\` text NULL, \`amount\` decimal(12,2) NOT NULL, \`type\` enum ('fixed', 'variable', 'one_time') NOT NULL DEFAULT 'variable', \`date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`recorded_by\` varchar(36) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`encryption_key\` (\`id\` varchar(36) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`name\` text NOT NULL, \`public_key\` text NULL, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`user_id\` varchar(36) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`encryption_data\` (\`id\` varchar(36) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`stored_encryption_data\` text NULL, \`stored_iv\` text NULL, \`stored_encryption_aes_key\` text NULL, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`key_id\` varchar(36) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cash\` (\`id\` varchar(36) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`date\` date NOT NULL, \`amount\` decimal(12,2) NOT NULL, \`type\` enum ('credit', 'debit') NOT NULL, \`note\` text NULL, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`cash_by\` varchar(36) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`folder\` ADD CONSTRAINT \`FK_afa55bd45385d7731c51de3eba3\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`folder\` ADD CONSTRAINT \`FK_ae991a4ac1bad2af0c06be6c560\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`folder\` ADD CONSTRAINT \`FK_82a84faa50e26fca20759bb3c24\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`folder\` ADD CONSTRAINT \`FK_fd89c6b76b9f8bdd18c3b8aa30a\` FOREIGN KEY (\`organization_id\`) REFERENCES \`organization\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`gallery\` ADD CONSTRAINT \`FK_0f74efc873fee52182bb4901e54\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`gallery\` ADD CONSTRAINT \`FK_73247f9d2e296742ae2e1b86980\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`gallery\` ADD CONSTRAINT \`FK_2254620b97af3786723cd5a8162\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`gallery\` ADD CONSTRAINT \`FK_6048ebaa4100a5d6d874468602d\` FOREIGN KEY (\`folder_id\`) REFERENCES \`folder\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`gallery\` ADD CONSTRAINT \`FK_6269b22b557dce812c46006fc5c\` FOREIGN KEY (\`organization_id\`) REFERENCES \`organization\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role\` ADD CONSTRAINT \`FK_04a09925beea59e864e921db4a1\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role\` ADD CONSTRAINT \`FK_858c871a036f61e56e2740c7cda\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role\` ADD CONSTRAINT \`FK_7b5b6fdd043b90e1d461b4b681d\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role\` ADD CONSTRAINT \`FK_2c1fc97f79b82800ef15372b98c\` FOREIGN KEY (\`organization_id\`) REFERENCES \`organization\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organization\` ADD CONSTRAINT \`FK_d348286667373cbcec5463cda5b\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organization\` ADD CONSTRAINT \`FK_b0c596f429ff2966d03516ef1ca\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organization\` ADD CONSTRAINT \`FK_edd3d199e09845da9c76636170a\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organization\` ADD CONSTRAINT \`FK_09e72692b015f30ba80789b3523\` FOREIGN KEY (\`image_id\`) REFERENCES \`gallery\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` ADD CONSTRAINT \`FK_334b3da6f12f406e929410bde33\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` ADD CONSTRAINT \`FK_5cbb84c0b66cf3351c388a3befd\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` ADD CONSTRAINT \`FK_e5f30f8b681a9589798d92d7d97\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` ADD CONSTRAINT \`FK_730c23f8bd493d0146d2bcf16b0\` FOREIGN KEY (\`image_id\`) REFERENCES \`gallery\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` ADD CONSTRAINT \`FK_95c4aa165f12726c58b02de0528\` FOREIGN KEY (\`parent_id\`) REFERENCES \`organization_branch\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` ADD CONSTRAINT \`FK_7d3afd6e0258e5483beaee5f652\` FOREIGN KEY (\`organization_id\`) REFERENCES \`organization\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`permission\` ADD CONSTRAINT \`FK_9c4a4f3953767dfc5d1a3b63d10\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`permission\` ADD CONSTRAINT \`FK_8a5117703b89f1cb83a44d895f3\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`permission\` ADD CONSTRAINT \`FK_974c86657cc409ff59ddb20b48b\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`menu\` ADD CONSTRAINT \`FK_592f239d67fb01e3db306325de5\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`menu\` ADD CONSTRAINT \`FK_07c2fb7633405194486e0ffc1ac\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`menu\` ADD CONSTRAINT \`FK_3480ccb9d92107de249e8e687d3\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`menu\` ADD CONSTRAINT \`FK_e5e28130fd17f88ab5ee5d3aa4c\` FOREIGN KEY (\`parent_id\`) REFERENCES \`menu\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`action\` ADD CONSTRAINT \`FK_513f1e020ad5ceafb38243fcc99\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`action\` ADD CONSTRAINT \`FK_fb357193ebb00db91b6c661e466\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`action\` ADD CONSTRAINT \`FK_d82f3c20a5a0ffd620f54e52d89\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`action\` ADD CONSTRAINT \`FK_6ffa6956165e8a372a397036544\` FOREIGN KEY (\`menu_id\`) REFERENCES \`menu\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`app\` ADD CONSTRAINT \`FK_abc737831ea5fc2566fd7c26546\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`app\` ADD CONSTRAINT \`FK_640611d2fbb4431a03335e8cf70\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`app\` ADD CONSTRAINT \`FK_ad5059c6e3c18fae76652ea263b\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`otp_validation\` ADD CONSTRAINT \`FK_c4481f02e27bd69089089d34ef7\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`otp_validation\` ADD CONSTRAINT \`FK_edfa210813fa9a16cfb2164584d\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`otp_validation\` ADD CONSTRAINT \`FK_d94f16071e43d84299dea42720c\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD CONSTRAINT \`FK_e4238c3828bc51ff8ca27c46385\` FOREIGN KEY (\`profile_picture_id\`) REFERENCES \`gallery\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` ADD CONSTRAINT \`FK_caa41b91f3c30a0f0a172187d9d\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` ADD CONSTRAINT \`FK_331edc6c04733098c74e3b39f81\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` ADD CONSTRAINT \`FK_316d2ef1146129a4d233863f823\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` ADD CONSTRAINT \`FK_26f4189498c6b038bfc624953c2\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` ADD CONSTRAINT \`FK_d39fdb10b9b1371666605df2a35\` FOREIGN KEY (\`nid_photo_id\`) REFERENCES \`gallery\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` ADD CONSTRAINT \`FK_961f12b246483a48d837dbbd557\` FOREIGN KEY (\`nominee_nid_photo_id\`) REFERENCES \`gallery\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` ADD CONSTRAINT \`FK_a23f383a4aaf0f6ec1c3ff64fe8\` FOREIGN KEY (\`refer_user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`expense\` ADD CONSTRAINT \`FK_d7f0f7ca79854cf3b8a6eb0265f\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`expense\` ADD CONSTRAINT \`FK_e03ae853c8541a99221514c8ae7\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`expense\` ADD CONSTRAINT \`FK_76027b498dcb26ee7074c6858dc\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`expense\` ADD CONSTRAINT \`FK_249ef73eec456a37c899e369941\` FOREIGN KEY (\`recorded_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`encryption_key\` ADD CONSTRAINT \`FK_16b36fc427c397ff6f4b5556e32\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`encryption_key\` ADD CONSTRAINT \`FK_74758295283264490d2b4131102\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`encryption_key\` ADD CONSTRAINT \`FK_bfd6c71c4f4e346866cdb004ae5\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`encryption_key\` ADD CONSTRAINT \`FK_47f17c13eaaf1af277381f34426\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`encryption_data\` ADD CONSTRAINT \`FK_d56cbd4b7f1a54b423ceff4dbb9\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`encryption_data\` ADD CONSTRAINT \`FK_db70fdc8dc17669f16f8709bd34\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`encryption_data\` ADD CONSTRAINT \`FK_5829cf889f80f1f690d2fd9a522\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`encryption_data\` ADD CONSTRAINT \`FK_1829cb37d0b1bbecb39838cf8c9\` FOREIGN KEY (\`key_id\`) REFERENCES \`encryption_key\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cash\` ADD CONSTRAINT \`FK_8f84d7e2fe678cfe0698d5c6c7a\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cash\` ADD CONSTRAINT \`FK_51811f839b26b081efe01f0935f\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cash\` ADD CONSTRAINT \`FK_7563aade7bf3f1fd27584ea620b\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cash\` ADD CONSTRAINT \`FK_badc477ee8c7f60784ffced5ccb\` FOREIGN KEY (\`cash_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`cash\` DROP FOREIGN KEY \`FK_badc477ee8c7f60784ffced5ccb\``);
        await queryRunner.query(`ALTER TABLE \`cash\` DROP FOREIGN KEY \`FK_7563aade7bf3f1fd27584ea620b\``);
        await queryRunner.query(`ALTER TABLE \`cash\` DROP FOREIGN KEY \`FK_51811f839b26b081efe01f0935f\``);
        await queryRunner.query(`ALTER TABLE \`cash\` DROP FOREIGN KEY \`FK_8f84d7e2fe678cfe0698d5c6c7a\``);
        await queryRunner.query(`ALTER TABLE \`encryption_data\` DROP FOREIGN KEY \`FK_1829cb37d0b1bbecb39838cf8c9\``);
        await queryRunner.query(`ALTER TABLE \`encryption_data\` DROP FOREIGN KEY \`FK_5829cf889f80f1f690d2fd9a522\``);
        await queryRunner.query(`ALTER TABLE \`encryption_data\` DROP FOREIGN KEY \`FK_db70fdc8dc17669f16f8709bd34\``);
        await queryRunner.query(`ALTER TABLE \`encryption_data\` DROP FOREIGN KEY \`FK_d56cbd4b7f1a54b423ceff4dbb9\``);
        await queryRunner.query(`ALTER TABLE \`encryption_key\` DROP FOREIGN KEY \`FK_47f17c13eaaf1af277381f34426\``);
        await queryRunner.query(`ALTER TABLE \`encryption_key\` DROP FOREIGN KEY \`FK_bfd6c71c4f4e346866cdb004ae5\``);
        await queryRunner.query(`ALTER TABLE \`encryption_key\` DROP FOREIGN KEY \`FK_74758295283264490d2b4131102\``);
        await queryRunner.query(`ALTER TABLE \`encryption_key\` DROP FOREIGN KEY \`FK_16b36fc427c397ff6f4b5556e32\``);
        await queryRunner.query(`ALTER TABLE \`expense\` DROP FOREIGN KEY \`FK_249ef73eec456a37c899e369941\``);
        await queryRunner.query(`ALTER TABLE \`expense\` DROP FOREIGN KEY \`FK_76027b498dcb26ee7074c6858dc\``);
        await queryRunner.query(`ALTER TABLE \`expense\` DROP FOREIGN KEY \`FK_e03ae853c8541a99221514c8ae7\``);
        await queryRunner.query(`ALTER TABLE \`expense\` DROP FOREIGN KEY \`FK_d7f0f7ca79854cf3b8a6eb0265f\``);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` DROP FOREIGN KEY \`FK_a23f383a4aaf0f6ec1c3ff64fe8\``);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` DROP FOREIGN KEY \`FK_961f12b246483a48d837dbbd557\``);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` DROP FOREIGN KEY \`FK_d39fdb10b9b1371666605df2a35\``);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` DROP FOREIGN KEY \`FK_26f4189498c6b038bfc624953c2\``);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` DROP FOREIGN KEY \`FK_316d2ef1146129a4d233863f823\``);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` DROP FOREIGN KEY \`FK_331edc6c04733098c74e3b39f81\``);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` DROP FOREIGN KEY \`FK_caa41b91f3c30a0f0a172187d9d\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP FOREIGN KEY \`FK_e4238c3828bc51ff8ca27c46385\``);
        await queryRunner.query(`ALTER TABLE \`otp_validation\` DROP FOREIGN KEY \`FK_d94f16071e43d84299dea42720c\``);
        await queryRunner.query(`ALTER TABLE \`otp_validation\` DROP FOREIGN KEY \`FK_edfa210813fa9a16cfb2164584d\``);
        await queryRunner.query(`ALTER TABLE \`otp_validation\` DROP FOREIGN KEY \`FK_c4481f02e27bd69089089d34ef7\``);
        await queryRunner.query(`ALTER TABLE \`app\` DROP FOREIGN KEY \`FK_ad5059c6e3c18fae76652ea263b\``);
        await queryRunner.query(`ALTER TABLE \`app\` DROP FOREIGN KEY \`FK_640611d2fbb4431a03335e8cf70\``);
        await queryRunner.query(`ALTER TABLE \`app\` DROP FOREIGN KEY \`FK_abc737831ea5fc2566fd7c26546\``);
        await queryRunner.query(`ALTER TABLE \`action\` DROP FOREIGN KEY \`FK_6ffa6956165e8a372a397036544\``);
        await queryRunner.query(`ALTER TABLE \`action\` DROP FOREIGN KEY \`FK_d82f3c20a5a0ffd620f54e52d89\``);
        await queryRunner.query(`ALTER TABLE \`action\` DROP FOREIGN KEY \`FK_fb357193ebb00db91b6c661e466\``);
        await queryRunner.query(`ALTER TABLE \`action\` DROP FOREIGN KEY \`FK_513f1e020ad5ceafb38243fcc99\``);
        await queryRunner.query(`ALTER TABLE \`menu\` DROP FOREIGN KEY \`FK_e5e28130fd17f88ab5ee5d3aa4c\``);
        await queryRunner.query(`ALTER TABLE \`menu\` DROP FOREIGN KEY \`FK_3480ccb9d92107de249e8e687d3\``);
        await queryRunner.query(`ALTER TABLE \`menu\` DROP FOREIGN KEY \`FK_07c2fb7633405194486e0ffc1ac\``);
        await queryRunner.query(`ALTER TABLE \`menu\` DROP FOREIGN KEY \`FK_592f239d67fb01e3db306325de5\``);
        await queryRunner.query(`ALTER TABLE \`permission\` DROP FOREIGN KEY \`FK_974c86657cc409ff59ddb20b48b\``);
        await queryRunner.query(`ALTER TABLE \`permission\` DROP FOREIGN KEY \`FK_8a5117703b89f1cb83a44d895f3\``);
        await queryRunner.query(`ALTER TABLE \`permission\` DROP FOREIGN KEY \`FK_9c4a4f3953767dfc5d1a3b63d10\``);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` DROP FOREIGN KEY \`FK_7d3afd6e0258e5483beaee5f652\``);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` DROP FOREIGN KEY \`FK_95c4aa165f12726c58b02de0528\``);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` DROP FOREIGN KEY \`FK_730c23f8bd493d0146d2bcf16b0\``);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` DROP FOREIGN KEY \`FK_e5f30f8b681a9589798d92d7d97\``);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` DROP FOREIGN KEY \`FK_5cbb84c0b66cf3351c388a3befd\``);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` DROP FOREIGN KEY \`FK_334b3da6f12f406e929410bde33\``);
        await queryRunner.query(`ALTER TABLE \`organization\` DROP FOREIGN KEY \`FK_09e72692b015f30ba80789b3523\``);
        await queryRunner.query(`ALTER TABLE \`organization\` DROP FOREIGN KEY \`FK_edd3d199e09845da9c76636170a\``);
        await queryRunner.query(`ALTER TABLE \`organization\` DROP FOREIGN KEY \`FK_b0c596f429ff2966d03516ef1ca\``);
        await queryRunner.query(`ALTER TABLE \`organization\` DROP FOREIGN KEY \`FK_d348286667373cbcec5463cda5b\``);
        await queryRunner.query(`ALTER TABLE \`role\` DROP FOREIGN KEY \`FK_2c1fc97f79b82800ef15372b98c\``);
        await queryRunner.query(`ALTER TABLE \`role\` DROP FOREIGN KEY \`FK_7b5b6fdd043b90e1d461b4b681d\``);
        await queryRunner.query(`ALTER TABLE \`role\` DROP FOREIGN KEY \`FK_858c871a036f61e56e2740c7cda\``);
        await queryRunner.query(`ALTER TABLE \`role\` DROP FOREIGN KEY \`FK_04a09925beea59e864e921db4a1\``);
        await queryRunner.query(`ALTER TABLE \`gallery\` DROP FOREIGN KEY \`FK_6269b22b557dce812c46006fc5c\``);
        await queryRunner.query(`ALTER TABLE \`gallery\` DROP FOREIGN KEY \`FK_6048ebaa4100a5d6d874468602d\``);
        await queryRunner.query(`ALTER TABLE \`gallery\` DROP FOREIGN KEY \`FK_2254620b97af3786723cd5a8162\``);
        await queryRunner.query(`ALTER TABLE \`gallery\` DROP FOREIGN KEY \`FK_73247f9d2e296742ae2e1b86980\``);
        await queryRunner.query(`ALTER TABLE \`gallery\` DROP FOREIGN KEY \`FK_0f74efc873fee52182bb4901e54\``);
        await queryRunner.query(`ALTER TABLE \`folder\` DROP FOREIGN KEY \`FK_fd89c6b76b9f8bdd18c3b8aa30a\``);
        await queryRunner.query(`ALTER TABLE \`folder\` DROP FOREIGN KEY \`FK_82a84faa50e26fca20759bb3c24\``);
        await queryRunner.query(`ALTER TABLE \`folder\` DROP FOREIGN KEY \`FK_ae991a4ac1bad2af0c06be6c560\``);
        await queryRunner.query(`ALTER TABLE \`folder\` DROP FOREIGN KEY \`FK_afa55bd45385d7731c51de3eba3\``);
        await queryRunner.query(`DROP TABLE \`cash\``);
        await queryRunner.query(`DROP TABLE \`encryption_data\``);
        await queryRunner.query(`DROP TABLE \`encryption_key\``);
        await queryRunner.query(`DROP TABLE \`expense\``);
        await queryRunner.query(`DROP TABLE \`user_personal_info\``);
        await queryRunner.query(`DROP INDEX \`IDX_e12875dfb3b1d92d7d7c5377e2\` ON \`user\``);
        await queryRunner.query(`DROP TABLE \`user\``);
        await queryRunner.query(`DROP INDEX \`IDX_64459517a9c0516dcfeb70fa7f\` ON \`otp_validation\``);
        await queryRunner.query(`DROP TABLE \`otp_validation\``);
        await queryRunner.query(`DROP INDEX \`IDX_8993112cd607f65268a4f57da3\` ON \`app\``);
        await queryRunner.query(`DROP INDEX \`IDX_f36adbb7b096ceeb6f3e80ad14\` ON \`app\``);
        await queryRunner.query(`DROP TABLE \`app\``);
        await queryRunner.query(`DROP INDEX \`IDX_e3f27529ac3d5b49ce85938917\` ON \`action\``);
        await queryRunner.query(`DROP INDEX \`IDX_a37ba4bbcb187af36aa07b86c7\` ON \`action\``);
        await queryRunner.query(`DROP INDEX \`IDX_4aa35beeebe7073b51be93aae6\` ON \`action\``);
        await queryRunner.query(`DROP TABLE \`action\``);
        await queryRunner.query(`DROP INDEX \`IDX_f37c203e9d061c884c4b034c83\` ON \`menu\``);
        await queryRunner.query(`DROP TABLE \`menu\``);
        await queryRunner.query(`DROP TABLE \`permission\``);
        await queryRunner.query(`DROP TABLE \`permission_history\``);
        await queryRunner.query(`DROP INDEX \`IDX_155ab20d89516db9cb05031f4f\` ON \`organization_branch\``);
        await queryRunner.query(`DROP TABLE \`organization_branch\``);
        await queryRunner.query(`DROP INDEX \`IDX_a08804baa7c5d5427067c49a31\` ON \`organization\``);
        await queryRunner.query(`DROP INDEX \`IDX_c21e615583a3ebbb0977452afb\` ON \`organization\``);
        await queryRunner.query(`DROP TABLE \`organization\``);
        await queryRunner.query(`DROP INDEX \`IDX_ae4578dcaed5adff96595e6166\` ON \`role\``);
        await queryRunner.query(`DROP TABLE \`role\``);
        await queryRunner.query(`DROP INDEX \`IDX_295fd6b6065fd46b418d79c6d0\` ON \`gallery\``);
        await queryRunner.query(`DROP TABLE \`gallery\``);
        await queryRunner.query(`DROP TABLE \`folder\``);
    }

}
