import { MigrationInterface, QueryRunner } from "typeorm";

export class Generate1758795386130 implements MigrationInterface {
    name = 'Generate1758795386130'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX \`IDX_295fd6b6065fd46b418d79c6d0\` ON \`gallery\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`user_generated_id\``);
        await queryRunner.query(`ALTER TABLE \`folder\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`folder\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`folder\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`folder\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`folder\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`folder\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`gallery\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`gallery\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`gallery\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`gallery\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`gallery\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`gallery\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`gallery\` DROP COLUMN \`url\``);
        await queryRunner.query(`ALTER TABLE \`gallery\` ADD \`url\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`role\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`role\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`role\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`role\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`role\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`role\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`organization\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`organization\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`organization\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`organization\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`organization\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`organization\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`organization\` DROP COLUMN \`phone\``);
        await queryRunner.query(`ALTER TABLE \`organization\` ADD \`phone\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` DROP COLUMN \`phone\``);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` ADD \`phone\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`permission_history\` DROP COLUMN \`subject_type\``);
        await queryRunner.query(`ALTER TABLE \`permission_history\` ADD \`subject_type\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`permission_history\` DROP COLUMN \`scope_type\``);
        await queryRunner.query(`ALTER TABLE \`permission_history\` ADD \`scope_type\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`permission_history\` DROP COLUMN \`action\``);
        await queryRunner.query(`ALTER TABLE \`permission_history\` ADD \`action\` varchar(10) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`permission_history\` DROP COLUMN \`timestamp\``);
        await queryRunner.query(`ALTER TABLE \`permission_history\` ADD \`timestamp\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`permission\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`permission\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`permission\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`permission\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`permission\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`permission\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`permission\` DROP COLUMN \`subject_type\``);
        await queryRunner.query(`ALTER TABLE \`permission\` ADD \`subject_type\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`permission\` DROP COLUMN \`scope_type\``);
        await queryRunner.query(`ALTER TABLE \`permission\` ADD \`scope_type\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`menu\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`menu\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`menu\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`menu\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`menu\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`menu\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`menu\` DROP COLUMN \`icon\``);
        await queryRunner.query(`ALTER TABLE \`menu\` ADD \`icon\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`action\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`action\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`action\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`action\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`action\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`action\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`app\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`app\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`app\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`app\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`app\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`app\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`app\` DROP COLUMN \`icon\``);
        await queryRunner.query(`ALTER TABLE \`app\` ADD \`icon\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`otp_validation\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`otp_validation\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`otp_validation\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`otp_validation\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`otp_validation\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`otp_validation\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`otp_validation\` DROP COLUMN \`value\``);
        await queryRunner.query(`ALTER TABLE \`otp_validation\` ADD \`value\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`password\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`password\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`email\` \`email\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`expense\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`expense\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`expense\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`expense\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`expense\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`expense\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`encryption_key\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`encryption_key\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`encryption_key\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`encryption_key\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`encryption_key\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`encryption_key\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`encryption_data\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`encryption_data\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`encryption_data\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`encryption_data\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`encryption_data\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`encryption_data\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`cash\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`cash\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`cash\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`cash\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`cash\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`cash\` ADD \`deleted_at\` timestamp(6) NULL`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`cash\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`cash\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`cash\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`cash\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`cash\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`cash\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`encryption_data\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`encryption_data\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`encryption_data\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`encryption_data\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`encryption_data\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`encryption_data\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`encryption_key\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`encryption_key\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`encryption_key\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`encryption_key\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`encryption_key\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`encryption_key\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`expense\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`expense\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`expense\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`expense\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`expense\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`expense\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`email\` \`email\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`password\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`password\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`otp_validation\` DROP COLUMN \`value\``);
        await queryRunner.query(`ALTER TABLE \`otp_validation\` ADD \`value\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`otp_validation\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`otp_validation\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`otp_validation\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`otp_validation\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`otp_validation\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`otp_validation\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`app\` DROP COLUMN \`icon\``);
        await queryRunner.query(`ALTER TABLE \`app\` ADD \`icon\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`app\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`app\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`app\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`app\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`app\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`app\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`action\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`action\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`action\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`action\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`action\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`action\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`menu\` DROP COLUMN \`icon\``);
        await queryRunner.query(`ALTER TABLE \`menu\` ADD \`icon\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`menu\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`menu\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`menu\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`menu\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`menu\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`menu\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`permission\` DROP COLUMN \`scope_type\``);
        await queryRunner.query(`ALTER TABLE \`permission\` ADD \`scope_type\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`permission\` DROP COLUMN \`subject_type\``);
        await queryRunner.query(`ALTER TABLE \`permission\` ADD \`subject_type\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`permission\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`permission\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`permission\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`permission\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`permission\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`permission\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`permission_history\` DROP COLUMN \`timestamp\``);
        await queryRunner.query(`ALTER TABLE \`permission_history\` ADD \`timestamp\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`permission_history\` DROP COLUMN \`action\``);
        await queryRunner.query(`ALTER TABLE \`permission_history\` ADD \`action\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`permission_history\` DROP COLUMN \`scope_type\``);
        await queryRunner.query(`ALTER TABLE \`permission_history\` ADD \`scope_type\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`permission_history\` DROP COLUMN \`subject_type\``);
        await queryRunner.query(`ALTER TABLE \`permission_history\` ADD \`subject_type\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` DROP COLUMN \`phone\``);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` ADD \`phone\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`organization_branch\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`organization\` DROP COLUMN \`phone\``);
        await queryRunner.query(`ALTER TABLE \`organization\` ADD \`phone\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`organization\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`organization\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`organization\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`organization\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`organization\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`organization\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`role\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`role\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`role\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`role\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`role\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`role\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`gallery\` DROP COLUMN \`url\``);
        await queryRunner.query(`ALTER TABLE \`gallery\` ADD \`url\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`gallery\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`gallery\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`gallery\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`gallery\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`gallery\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`gallery\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`folder\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`folder\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`folder\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`folder\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`folder\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`folder\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`user_generated_id\` varchar(255) CHARACTER SET "latin1" COLLATE "latin1_swedish_ci" NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_295fd6b6065fd46b418d79c6d0\` ON \`gallery\` (\`url\`)`);
    }

}
