import { MigrationInterface, QueryRunner } from "typeorm";

export class Generate1758499560431 implements MigrationInterface {
    name = 'Generate1758499560431'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`c\` (\`id\` varchar(36) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`name\` varchar(255) NOT NULL, \`slug\` varchar(255) NOT NULL, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`organization_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`n\` (\`id\` varchar(36) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`name\` varchar(255) NOT NULL, \`url\` varchar(500) NOT NULL, \`type\` varchar(255) NOT NULL, \`size\` varchar(255) NOT NULL, \`is_private\` tinyint NOT NULL DEFAULT 0, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`folder_id\` varchar(36) NULL, \`organization_id\` varchar(36) NULL, UNIQUE INDEX \`IDX_599e494d31a8519938ea737042\` (\`url\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`t\` (\`id\` varchar(36) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`name\` varchar(255) NOT NULL, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`organization_id\` varchar(36) NULL, UNIQUE INDEX \`IDX_8c3be9ddfa88ba30de57dd6c59\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`a\` (\`id\` varchar(36) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`read_only\` tinyint NOT NULL DEFAULT 0, \`name\` varchar(255) NOT NULL, \`slug\` varchar(255) NOT NULL, \`address\` longtext NULL, \`phone\` varchar(50) NULL, \`email\` varchar(255) NULL, \`serial\` int NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`additional_fields\` json NULL, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`image_id\` varchar(36) NULL, UNIQUE INDEX \`IDX_22dbbd0f5de760a44cf2f276ef\` (\`name\`), UNIQUE INDEX \`IDX_a1c4c21082d04f429416d779d3\` (\`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`r\` (\`id\` varchar(36) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`read_only\` tinyint NOT NULL DEFAULT 0, \`name\` varchar(255) NOT NULL, \`slug\` varchar(255) NOT NULL, \`address\` longtext NULL, \`phone\` varchar(50) NULL, \`email\` varchar(255) NULL, \`serial\` int NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`image_id\` varchar(36) NULL, \`parent_id\` varchar(36) NULL, \`organization_id\` varchar(36) NULL, UNIQUE INDEX \`IDX_4ecd43fabc743cfd668a41e79f\` (\`organization_id\`, \`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`f\` (\`id\` int NOT NULL AUTO_INCREMENT, \`permission_id\` varchar(255) NOT NULL, \`subject_type\` varchar(100) NOT NULL, \`subject_id\` varchar(255) NOT NULL, \`scope_type\` varchar(100) NOT NULL, \`scope_id\` varchar(255) NOT NULL, \`action\` varchar(10) NOT NULL, \`previous_value\` json NULL, \`new_value\` json NULL, \`timestamp\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`performed_by\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`h\` (\`id\` varchar(36) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`subject_type\` varchar(100) NOT NULL, \`subject_id\` varchar(255) NOT NULL, \`scope_type\` varchar(100) NOT NULL, \`scope_id\` varchar(255) NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`type\` int NULL, \`organization_branch_id\` varchar(255) NULL, \`organization_id\` varchar(255) NULL, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`p\` (\`id\` varchar(36) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`groups\` text NOT NULL, \`name\` varchar(255) NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`icon_type\` int NOT NULL DEFAULT '1', \`icon\` varchar(255) NULL, \`router_link\` varchar(255) NULL, \`serial\` int NULL, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`parent_id\` varchar(36) NULL, UNIQUE INDEX \`IDX_6839a59cfd10aed43ab3efa88f\` (\`name\`, \`parent_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`v\` (\`id\` varchar(36) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`groups\` text NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`name\` varchar(255) NOT NULL, \`url\` varchar(255) NOT NULL, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`menu_id\` varchar(36) NULL, UNIQUE INDEX \`IDX_ed8aa30212707c6513221bb2ed\` (\`name\`), UNIQUE INDEX \`IDX_cdcd4e32014c26aea331ccb32c\` (\`url\`), UNIQUE INDEX \`IDX_78d575b980a3d678c1b01aff35\` (\`url\`, \`menu_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`_\` (\`id\` varchar(36) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`client_request_id\` varchar(255) NOT NULL, \`value\` varchar(50) NOT NULL, \`code\` int NOT NULL, \`is_verified\` tinyint NOT NULL DEFAULT 0, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, UNIQUE INDEX \`IDX_39bffe4a6d20acebca34fd2887\` (\`client_request_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`x\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NULL, \`phone\` varchar(255) NULL, \`password\` text NULL, \`email\` varchar(255) NOT NULL, \`user_generated_id\` varchar(255) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`profile_picture_id\` varchar(36) NULL, UNIQUE INDEX \`IDX_18c87582b368db5cfa0caeff7b\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_personal_info\` (\`id\` varchar(36) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`father_name\` varchar(255) NULL, \`mother_name\` varchar(255) NULL, \`marital_status\` varchar(255) NULL, \`present_address\` text NULL, \`permanent_address\` text NULL, \`profession\` varchar(255) NULL, \`nominee_name\` varchar(255) NULL, \`relation_with_nominee\` varchar(255) NULL, \`comments\` text NULL, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`user_id\` varchar(36) NOT NULL, \`nid_photo_id\` varchar(36) NULL, \`nominee_nid_photo_id\` varchar(36) NULL, \`refer_user_id\` varchar(36) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`expense\` (\`id\` varchar(36) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`title\` varchar(200) NOT NULL, \`description\` text NULL, \`amount\` decimal(12,2) NOT NULL, \`type\` enum ('fixed', 'variable', 'one_time') NOT NULL DEFAULT 'variable', \`date\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`recorded_by\` varchar(36) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`encryption_key\` (\`id\` varchar(36) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`name\` text NOT NULL, \`public_key\` text NULL, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`user_id\` varchar(36) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`encryption_data\` (\`id\` varchar(36) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`stored_encryption_data\` text NULL, \`stored_iv\` text NULL, \`stored_encryption_aes_key\` text NULL, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`key_id\` varchar(36) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cash\` (\`id\` varchar(36) NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` timestamp(6) NULL, \`date\` date NOT NULL, \`amount\` decimal(12,2) NOT NULL, \`type\` enum ('credit', 'debit') NOT NULL, \`note\` text NULL, \`created_by\` varchar(36) NULL, \`updated_by\` varchar(36) NULL, \`deleted_by\` varchar(36) NULL, \`cash_by\` varchar(36) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`c\` DROP COLUMN \`organization_id\``);
        await queryRunner.query(`ALTER TABLE \`c\` ADD \`organization_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`c\` ADD \`is_active\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`c\` ADD \`icon_type\` int NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`c\` ADD \`icon\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`c\` ADD \`is_external\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`c\` ADD \`external_link\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`c\` ADD UNIQUE INDEX \`IDX_85f186b132c58fabb99858f942\` (\`name\`)`);
        await queryRunner.query(`ALTER TABLE \`c\` ADD UNIQUE INDEX \`IDX_e717435ef074bab20fe4765745\` (\`slug\`)`);
        await queryRunner.query(`ALTER TABLE \`c\` ADD CONSTRAINT \`FK_fc127bb8d73845a1b0a40870f1e\` FOREIGN KEY (\`created_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`c\` ADD CONSTRAINT \`FK_95d99feaf3f2202e09fcb28af9a\` FOREIGN KEY (\`updated_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`c\` ADD CONSTRAINT \`FK_3e2a33909842e32abdfdcc56d9a\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`c\` ADD CONSTRAINT \`FK_c042c9b64bb3ab82b8cd2628078\` FOREIGN KEY (\`organization_id\`) REFERENCES \`a\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`n\` ADD CONSTRAINT \`FK_83b062e807c1eb0a5e649c268df\` FOREIGN KEY (\`created_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`n\` ADD CONSTRAINT \`FK_a0412cde9717388d164b207fec8\` FOREIGN KEY (\`updated_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`n\` ADD CONSTRAINT \`FK_853cab80d9dab9163444c059741\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`n\` ADD CONSTRAINT \`FK_27597935a99ff421185aab412cf\` FOREIGN KEY (\`folder_id\`) REFERENCES \`c\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`n\` ADD CONSTRAINT \`FK_eb20744a79d9aaf95409dc8a00b\` FOREIGN KEY (\`organization_id\`) REFERENCES \`a\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`t\` ADD CONSTRAINT \`FK_8d1517cf4b1c38593a27b79a38d\` FOREIGN KEY (\`created_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`t\` ADD CONSTRAINT \`FK_3348fabf848f8f6b42348100798\` FOREIGN KEY (\`updated_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`t\` ADD CONSTRAINT \`FK_8592be87ea9432e64b1a4a304a9\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`t\` ADD CONSTRAINT \`FK_0851c67ee9c5150c92566348626\` FOREIGN KEY (\`organization_id\`) REFERENCES \`a\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`a\` ADD CONSTRAINT \`FK_30a3fd7c92a3f3415d864fb8a3d\` FOREIGN KEY (\`created_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`a\` ADD CONSTRAINT \`FK_021ecbce5a044c2855f06ca7d0d\` FOREIGN KEY (\`updated_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`a\` ADD CONSTRAINT \`FK_f306168aa8bcf2eb8a7c5660a11\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`a\` ADD CONSTRAINT \`FK_6e400736919e24e53a25b013f73\` FOREIGN KEY (\`image_id\`) REFERENCES \`n\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`r\` ADD CONSTRAINT \`FK_e10fc451d61c202e84dfb2294dd\` FOREIGN KEY (\`created_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`r\` ADD CONSTRAINT \`FK_9bbb598aeb870f7a6748d2c9104\` FOREIGN KEY (\`updated_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`r\` ADD CONSTRAINT \`FK_25c94c8d551b70128f5ca37d669\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`r\` ADD CONSTRAINT \`FK_6c47022cd0fe5584736758ba33d\` FOREIGN KEY (\`image_id\`) REFERENCES \`n\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`r\` ADD CONSTRAINT \`FK_21e37c2cc15035dcd639c176195\` FOREIGN KEY (\`parent_id\`) REFERENCES \`r\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`r\` ADD CONSTRAINT \`FK_6ed9a8634b31cb67b8d5ffd382b\` FOREIGN KEY (\`organization_id\`) REFERENCES \`a\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`h\` ADD CONSTRAINT \`FK_f90129969fa4890fc5cb42062ee\` FOREIGN KEY (\`created_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`h\` ADD CONSTRAINT \`FK_dab04d2d34f2cd83369ddc11f9b\` FOREIGN KEY (\`updated_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`h\` ADD CONSTRAINT \`FK_fd1fd70ab0450b22619e0c60b53\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`p\` ADD CONSTRAINT \`FK_44e2b377cbcaae2dc2988309aff\` FOREIGN KEY (\`created_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`p\` ADD CONSTRAINT \`FK_cfec263d581113599e92695f06b\` FOREIGN KEY (\`updated_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`p\` ADD CONSTRAINT \`FK_b2f17a15b032db9a333f3117898\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`p\` ADD CONSTRAINT \`FK_9c614bf8dcedf3909929b298184\` FOREIGN KEY (\`parent_id\`) REFERENCES \`p\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`v\` ADD CONSTRAINT \`FK_c244ca065d032e11af6003b8fa3\` FOREIGN KEY (\`created_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`v\` ADD CONSTRAINT \`FK_4ecbae2cd61aa3adf2acd7f3e21\` FOREIGN KEY (\`updated_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`v\` ADD CONSTRAINT \`FK_ed921041c2b91c8653fe269115d\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`v\` ADD CONSTRAINT \`FK_b6b21d26463355445a31e118f4e\` FOREIGN KEY (\`menu_id\`) REFERENCES \`p\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`_\` ADD CONSTRAINT \`FK_39422b991b972b92d9472f93f18\` FOREIGN KEY (\`created_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`_\` ADD CONSTRAINT \`FK_7e50341e4861fec23743d159c67\` FOREIGN KEY (\`updated_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`_\` ADD CONSTRAINT \`FK_e70d4435494d77c5185fe227846\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`x\` ADD CONSTRAINT \`FK_d8afa72aaafb7f33fbffbc83f09\` FOREIGN KEY (\`profile_picture_id\`) REFERENCES \`n\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` ADD CONSTRAINT \`FK_caa41b91f3c30a0f0a172187d9d\` FOREIGN KEY (\`created_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` ADD CONSTRAINT \`FK_331edc6c04733098c74e3b39f81\` FOREIGN KEY (\`updated_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` ADD CONSTRAINT \`FK_316d2ef1146129a4d233863f823\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` ADD CONSTRAINT \`FK_26f4189498c6b038bfc624953c2\` FOREIGN KEY (\`user_id\`) REFERENCES \`x\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` ADD CONSTRAINT \`FK_d39fdb10b9b1371666605df2a35\` FOREIGN KEY (\`nid_photo_id\`) REFERENCES \`n\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` ADD CONSTRAINT \`FK_961f12b246483a48d837dbbd557\` FOREIGN KEY (\`nominee_nid_photo_id\`) REFERENCES \`n\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` ADD CONSTRAINT \`FK_a23f383a4aaf0f6ec1c3ff64fe8\` FOREIGN KEY (\`refer_user_id\`) REFERENCES \`x\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`expense\` ADD CONSTRAINT \`FK_d7f0f7ca79854cf3b8a6eb0265f\` FOREIGN KEY (\`created_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`expense\` ADD CONSTRAINT \`FK_e03ae853c8541a99221514c8ae7\` FOREIGN KEY (\`updated_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`expense\` ADD CONSTRAINT \`FK_76027b498dcb26ee7074c6858dc\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`expense\` ADD CONSTRAINT \`FK_249ef73eec456a37c899e369941\` FOREIGN KEY (\`recorded_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`encryption_key\` ADD CONSTRAINT \`FK_16b36fc427c397ff6f4b5556e32\` FOREIGN KEY (\`created_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`encryption_key\` ADD CONSTRAINT \`FK_74758295283264490d2b4131102\` FOREIGN KEY (\`updated_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`encryption_key\` ADD CONSTRAINT \`FK_bfd6c71c4f4e346866cdb004ae5\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`encryption_key\` ADD CONSTRAINT \`FK_47f17c13eaaf1af277381f34426\` FOREIGN KEY (\`user_id\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`encryption_data\` ADD CONSTRAINT \`FK_d56cbd4b7f1a54b423ceff4dbb9\` FOREIGN KEY (\`created_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`encryption_data\` ADD CONSTRAINT \`FK_db70fdc8dc17669f16f8709bd34\` FOREIGN KEY (\`updated_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`encryption_data\` ADD CONSTRAINT \`FK_5829cf889f80f1f690d2fd9a522\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`encryption_data\` ADD CONSTRAINT \`FK_1829cb37d0b1bbecb39838cf8c9\` FOREIGN KEY (\`key_id\`) REFERENCES \`encryption_key\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cash\` ADD CONSTRAINT \`FK_8f84d7e2fe678cfe0698d5c6c7a\` FOREIGN KEY (\`created_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cash\` ADD CONSTRAINT \`FK_51811f839b26b081efe01f0935f\` FOREIGN KEY (\`updated_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cash\` ADD CONSTRAINT \`FK_7563aade7bf3f1fd27584ea620b\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cash\` ADD CONSTRAINT \`FK_badc477ee8c7f60784ffced5ccb\` FOREIGN KEY (\`cash_by\`) REFERENCES \`x\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`cash\` DROP FOREIGN KEY \`FK_badc477ee8c7f60784ffced5ccb\``);
        await queryRunner.query(`ALTER TABLE \`cash\` DROP FOREIGN KEY \`FK_7563aade7bf3f1fd27584ea620b\``);
        await queryRunner.query(`ALTER TABLE \`cash\` DROP FOREIGN KEY \`FK_51811f839b26b081efe01f0935f\``);
        await queryRunner.query(`ALTER TABLE \`cash\` DROP FOREIGN KEY \`FK_8f84d7e2fe678cfe0698d5c6c7a\``);
        await queryRunner.query(`ALTER TABLE \`encryption_data\` DROP FOREIGN KEY \`FK_1829cb37d0b1bbecb39838cf8c9\``);
        await queryRunner.query(`ALTER TABLE \`encryption_data\` DROP FOREIGN KEY \`FK_5829cf889f80f1f690d2fd9a522\``);
        await queryRunner.query(`ALTER TABLE \`encryption_data\` DROP FOREIGN KEY \`FK_db70fdc8dc17669f16f8709bd34\``);
        await queryRunner.query(`ALTER TABLE \`encryption_data\` DROP FOREIGN KEY \`FK_d56cbd4b7f1a54b423ceff4dbb9\``);
        await queryRunner.query(`ALTER TABLE \`encryption_key\` DROP FOREIGN KEY \`FK_47f17c13eaaf1af277381f34426\``);
        await queryRunner.query(`ALTER TABLE \`encryption_key\` DROP FOREIGN KEY \`FK_bfd6c71c4f4e346866cdb004ae5\``);
        await queryRunner.query(`ALTER TABLE \`encryption_key\` DROP FOREIGN KEY \`FK_74758295283264490d2b4131102\``);
        await queryRunner.query(`ALTER TABLE \`encryption_key\` DROP FOREIGN KEY \`FK_16b36fc427c397ff6f4b5556e32\``);
        await queryRunner.query(`ALTER TABLE \`expense\` DROP FOREIGN KEY \`FK_249ef73eec456a37c899e369941\``);
        await queryRunner.query(`ALTER TABLE \`expense\` DROP FOREIGN KEY \`FK_76027b498dcb26ee7074c6858dc\``);
        await queryRunner.query(`ALTER TABLE \`expense\` DROP FOREIGN KEY \`FK_e03ae853c8541a99221514c8ae7\``);
        await queryRunner.query(`ALTER TABLE \`expense\` DROP FOREIGN KEY \`FK_d7f0f7ca79854cf3b8a6eb0265f\``);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` DROP FOREIGN KEY \`FK_a23f383a4aaf0f6ec1c3ff64fe8\``);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` DROP FOREIGN KEY \`FK_961f12b246483a48d837dbbd557\``);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` DROP FOREIGN KEY \`FK_d39fdb10b9b1371666605df2a35\``);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` DROP FOREIGN KEY \`FK_26f4189498c6b038bfc624953c2\``);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` DROP FOREIGN KEY \`FK_316d2ef1146129a4d233863f823\``);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` DROP FOREIGN KEY \`FK_331edc6c04733098c74e3b39f81\``);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` DROP FOREIGN KEY \`FK_caa41b91f3c30a0f0a172187d9d\``);
        await queryRunner.query(`ALTER TABLE \`x\` DROP FOREIGN KEY \`FK_d8afa72aaafb7f33fbffbc83f09\``);
        await queryRunner.query(`ALTER TABLE \`_\` DROP FOREIGN KEY \`FK_e70d4435494d77c5185fe227846\``);
        await queryRunner.query(`ALTER TABLE \`_\` DROP FOREIGN KEY \`FK_7e50341e4861fec23743d159c67\``);
        await queryRunner.query(`ALTER TABLE \`_\` DROP FOREIGN KEY \`FK_39422b991b972b92d9472f93f18\``);
        await queryRunner.query(`ALTER TABLE \`v\` DROP FOREIGN KEY \`FK_b6b21d26463355445a31e118f4e\``);
        await queryRunner.query(`ALTER TABLE \`v\` DROP FOREIGN KEY \`FK_ed921041c2b91c8653fe269115d\``);
        await queryRunner.query(`ALTER TABLE \`v\` DROP FOREIGN KEY \`FK_4ecbae2cd61aa3adf2acd7f3e21\``);
        await queryRunner.query(`ALTER TABLE \`v\` DROP FOREIGN KEY \`FK_c244ca065d032e11af6003b8fa3\``);
        await queryRunner.query(`ALTER TABLE \`p\` DROP FOREIGN KEY \`FK_9c614bf8dcedf3909929b298184\``);
        await queryRunner.query(`ALTER TABLE \`p\` DROP FOREIGN KEY \`FK_b2f17a15b032db9a333f3117898\``);
        await queryRunner.query(`ALTER TABLE \`p\` DROP FOREIGN KEY \`FK_cfec263d581113599e92695f06b\``);
        await queryRunner.query(`ALTER TABLE \`p\` DROP FOREIGN KEY \`FK_44e2b377cbcaae2dc2988309aff\``);
        await queryRunner.query(`ALTER TABLE \`h\` DROP FOREIGN KEY \`FK_fd1fd70ab0450b22619e0c60b53\``);
        await queryRunner.query(`ALTER TABLE \`h\` DROP FOREIGN KEY \`FK_dab04d2d34f2cd83369ddc11f9b\``);
        await queryRunner.query(`ALTER TABLE \`h\` DROP FOREIGN KEY \`FK_f90129969fa4890fc5cb42062ee\``);
        await queryRunner.query(`ALTER TABLE \`r\` DROP FOREIGN KEY \`FK_6ed9a8634b31cb67b8d5ffd382b\``);
        await queryRunner.query(`ALTER TABLE \`r\` DROP FOREIGN KEY \`FK_21e37c2cc15035dcd639c176195\``);
        await queryRunner.query(`ALTER TABLE \`r\` DROP FOREIGN KEY \`FK_6c47022cd0fe5584736758ba33d\``);
        await queryRunner.query(`ALTER TABLE \`r\` DROP FOREIGN KEY \`FK_25c94c8d551b70128f5ca37d669\``);
        await queryRunner.query(`ALTER TABLE \`r\` DROP FOREIGN KEY \`FK_9bbb598aeb870f7a6748d2c9104\``);
        await queryRunner.query(`ALTER TABLE \`r\` DROP FOREIGN KEY \`FK_e10fc451d61c202e84dfb2294dd\``);
        await queryRunner.query(`ALTER TABLE \`a\` DROP FOREIGN KEY \`FK_6e400736919e24e53a25b013f73\``);
        await queryRunner.query(`ALTER TABLE \`a\` DROP FOREIGN KEY \`FK_f306168aa8bcf2eb8a7c5660a11\``);
        await queryRunner.query(`ALTER TABLE \`a\` DROP FOREIGN KEY \`FK_021ecbce5a044c2855f06ca7d0d\``);
        await queryRunner.query(`ALTER TABLE \`a\` DROP FOREIGN KEY \`FK_30a3fd7c92a3f3415d864fb8a3d\``);
        await queryRunner.query(`ALTER TABLE \`t\` DROP FOREIGN KEY \`FK_0851c67ee9c5150c92566348626\``);
        await queryRunner.query(`ALTER TABLE \`t\` DROP FOREIGN KEY \`FK_8592be87ea9432e64b1a4a304a9\``);
        await queryRunner.query(`ALTER TABLE \`t\` DROP FOREIGN KEY \`FK_3348fabf848f8f6b42348100798\``);
        await queryRunner.query(`ALTER TABLE \`t\` DROP FOREIGN KEY \`FK_8d1517cf4b1c38593a27b79a38d\``);
        await queryRunner.query(`ALTER TABLE \`n\` DROP FOREIGN KEY \`FK_eb20744a79d9aaf95409dc8a00b\``);
        await queryRunner.query(`ALTER TABLE \`n\` DROP FOREIGN KEY \`FK_27597935a99ff421185aab412cf\``);
        await queryRunner.query(`ALTER TABLE \`n\` DROP FOREIGN KEY \`FK_853cab80d9dab9163444c059741\``);
        await queryRunner.query(`ALTER TABLE \`n\` DROP FOREIGN KEY \`FK_a0412cde9717388d164b207fec8\``);
        await queryRunner.query(`ALTER TABLE \`n\` DROP FOREIGN KEY \`FK_83b062e807c1eb0a5e649c268df\``);
        await queryRunner.query(`ALTER TABLE \`c\` DROP FOREIGN KEY \`FK_c042c9b64bb3ab82b8cd2628078\``);
        await queryRunner.query(`ALTER TABLE \`c\` DROP FOREIGN KEY \`FK_3e2a33909842e32abdfdcc56d9a\``);
        await queryRunner.query(`ALTER TABLE \`c\` DROP FOREIGN KEY \`FK_95d99feaf3f2202e09fcb28af9a\``);
        await queryRunner.query(`ALTER TABLE \`c\` DROP FOREIGN KEY \`FK_fc127bb8d73845a1b0a40870f1e\``);
        await queryRunner.query(`ALTER TABLE \`c\` DROP INDEX \`IDX_e717435ef074bab20fe4765745\``);
        await queryRunner.query(`ALTER TABLE \`c\` DROP INDEX \`IDX_85f186b132c58fabb99858f942\``);
        await queryRunner.query(`ALTER TABLE \`c\` DROP COLUMN \`external_link\``);
        await queryRunner.query(`ALTER TABLE \`c\` DROP COLUMN \`is_external\``);
        await queryRunner.query(`ALTER TABLE \`c\` DROP COLUMN \`icon\``);
        await queryRunner.query(`ALTER TABLE \`c\` DROP COLUMN \`icon_type\``);
        await queryRunner.query(`ALTER TABLE \`c\` DROP COLUMN \`is_active\``);
        await queryRunner.query(`ALTER TABLE \`c\` DROP COLUMN \`organization_id\``);
        await queryRunner.query(`ALTER TABLE \`c\` ADD \`organization_id\` varchar(36) NULL`);
        await queryRunner.query(`DROP TABLE \`cash\``);
        await queryRunner.query(`DROP TABLE \`encryption_data\``);
        await queryRunner.query(`DROP TABLE \`encryption_key\``);
        await queryRunner.query(`DROP TABLE \`expense\``);
        await queryRunner.query(`DROP TABLE \`user_personal_info\``);
        await queryRunner.query(`DROP INDEX \`IDX_18c87582b368db5cfa0caeff7b\` ON \`x\``);
        await queryRunner.query(`DROP TABLE \`x\``);
        await queryRunner.query(`DROP INDEX \`IDX_39bffe4a6d20acebca34fd2887\` ON \`_\``);
        await queryRunner.query(`DROP TABLE \`_\``);
        await queryRunner.query(`DROP INDEX \`IDX_78d575b980a3d678c1b01aff35\` ON \`v\``);
        await queryRunner.query(`DROP INDEX \`IDX_cdcd4e32014c26aea331ccb32c\` ON \`v\``);
        await queryRunner.query(`DROP INDEX \`IDX_ed8aa30212707c6513221bb2ed\` ON \`v\``);
        await queryRunner.query(`DROP TABLE \`v\``);
        await queryRunner.query(`DROP INDEX \`IDX_6839a59cfd10aed43ab3efa88f\` ON \`p\``);
        await queryRunner.query(`DROP TABLE \`p\``);
        await queryRunner.query(`DROP TABLE \`h\``);
        await queryRunner.query(`DROP TABLE \`f\``);
        await queryRunner.query(`DROP INDEX \`IDX_4ecd43fabc743cfd668a41e79f\` ON \`r\``);
        await queryRunner.query(`DROP TABLE \`r\``);
        await queryRunner.query(`DROP INDEX \`IDX_a1c4c21082d04f429416d779d3\` ON \`a\``);
        await queryRunner.query(`DROP INDEX \`IDX_22dbbd0f5de760a44cf2f276ef\` ON \`a\``);
        await queryRunner.query(`DROP TABLE \`a\``);
        await queryRunner.query(`DROP INDEX \`IDX_8c3be9ddfa88ba30de57dd6c59\` ON \`t\``);
        await queryRunner.query(`DROP TABLE \`t\``);
        await queryRunner.query(`DROP INDEX \`IDX_599e494d31a8519938ea737042\` ON \`n\``);
        await queryRunner.query(`DROP TABLE \`n\``);
        await queryRunner.query(`DROP TABLE \`c\``);
    }

}
