import { MigrationInterface, QueryRunner } from "typeorm";

export class Generate1753087287364 implements MigrationInterface {
    name = 'Generate1753087287364'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`folder\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`name\` varchar(255) NOT NULL, \`slug\` varchar(255) NOT NULL, \`created_by\` int NULL, \`updated_by\` int NULL, \`deleted_by\` int NULL, \`company_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`gallery\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`name\` varchar(255) NOT NULL, \`url\` varchar(255) NOT NULL, \`type\` varchar(255) NOT NULL, \`size\` varchar(255) NOT NULL, \`is_private\` tinyint NOT NULL DEFAULT 0, \`created_by\` int NULL, \`updated_by\` int NULL, \`deleted_by\` int NULL, \`folder_id\` int NULL, \`company_id\` int NULL, UNIQUE INDEX \`IDX_295fd6b6065fd46b418d79c6d0\` (\`url\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`role_action\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`read_only\` tinyint NOT NULL DEFAULT 0, \`created_by\` int NULL, \`updated_by\` int NULL, \`deleted_by\` int NULL, \`action_id\` int NOT NULL, \`role_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`action\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`name\` varchar(255) NOT NULL, \`url\` varchar(255) NOT NULL, \`created_by\` int NULL, \`updated_by\` int NULL, \`deleted_by\` int NULL, \`menu_id\` int NULL, UNIQUE INDEX \`IDX_4aa35beeebe7073b51be93aae6\` (\`name\`), UNIQUE INDEX \`IDX_a37ba4bbcb187af36aa07b86c7\` (\`url\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_action\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`read_only\` tinyint NOT NULL DEFAULT 0, \`type\` enum ('1', '2', '3') NOT NULL DEFAULT '1', \`created_by\` int NULL, \`updated_by\` int NULL, \`deleted_by\` int NULL, \`action_id\` int NOT NULL, \`user_id\` int NOT NULL, \`company_branch_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_role\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`read_only\` tinyint NOT NULL DEFAULT 0, \`created_by\` int NULL, \`updated_by\` int NULL, \`deleted_by\` int NULL, \`role_id\` int NOT NULL, \`user_id\` int NOT NULL, \`company_branch_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_company\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`read_only\` tinyint NOT NULL DEFAULT 0, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_by\` int NULL, \`updated_by\` int NULL, \`deleted_by\` int NULL, \`company_id\` int NOT NULL, \`user_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_company_branch\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`read_only\` tinyint NOT NULL DEFAULT 0, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_by\` int NULL, \`updated_by\` int NULL, \`deleted_by\` int NULL, \`company_id\` int NOT NULL, \`user_id\` int NOT NULL, \`company_branch_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NULL, \`phone\` varchar(255) NULL, \`password\` varchar(255) NULL, \`email\` varchar(255) NULL, \`user_generated_id\` varchar(255) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`profile_picture_id\` int NULL, UNIQUE INDEX \`IDX_e12875dfb3b1d92d7d7c5377e2\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_menu\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`read_only\` tinyint NOT NULL DEFAULT 0, \`type\` enum ('1', '2', '3') NOT NULL DEFAULT '1', \`created_by\` int NULL, \`updated_by\` int NULL, \`deleted_by\` int NULL, \`menu_id\` int NOT NULL, \`user_id\` int NOT NULL, \`company_branch_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`menu\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`read_only\` tinyint NOT NULL DEFAULT 0, \`name\` varchar(255) NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`icon\` varchar(255) NULL, \`router_link\` varchar(255) NULL, \`serial\` int NULL, \`created_by\` int NULL, \`updated_by\` int NULL, \`deleted_by\` int NULL, \`parent_id\` int NULL, UNIQUE INDEX \`IDX_f37c203e9d061c884c4b034c83\` (\`name\`, \`parent_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`role_menu\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`read_only\` tinyint NOT NULL DEFAULT 0, \`created_by\` int NULL, \`updated_by\` int NULL, \`deleted_by\` int NULL, \`menu_id\` int NOT NULL, \`role_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`role\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`name\` varchar(255) NOT NULL, \`created_by\` int NULL, \`updated_by\` int NULL, \`deleted_by\` int NULL, \`company_id\` int NULL, UNIQUE INDEX \`IDX_ae4578dcaed5adff96595e6166\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`company\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`read_only\` tinyint NOT NULL DEFAULT 0, \`name\` varchar(255) NOT NULL, \`slug\` varchar(255) NOT NULL, \`address\` longtext NULL, \`phone\` varchar(255) NULL, \`email\` varchar(255) NULL, \`serial\` int NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_by\` int NULL, \`updated_by\` int NULL, \`deleted_by\` int NULL, \`image_id\` int NULL, UNIQUE INDEX \`IDX_a76c5cd486f7779bd9c319afd2\` (\`name\`), UNIQUE INDEX \`IDX_47216baa0f0c8ebc6ee5a74989\` (\`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`company_branch\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`read_only\` tinyint NOT NULL DEFAULT 0, \`name\` varchar(255) NOT NULL, \`slug\` varchar(255) NOT NULL, \`address\` longtext NULL, \`phone\` varchar(255) NULL, \`email\` varchar(255) NULL, \`serial\` int NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_by\` int NULL, \`updated_by\` int NULL, \`deleted_by\` int NULL, \`image_id\` int NULL, \`parent_id\` int NULL, \`company_id\` int NULL, UNIQUE INDEX \`IDX_6bcfe5fa6ded76d85ca7f8ff08\` (\`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`otp_validation\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`client_request_id\` varchar(255) NOT NULL, \`value\` varchar(255) NOT NULL, \`code\` int NOT NULL, \`is_verified\` tinyint NOT NULL DEFAULT 0, \`created_by\` int NULL, \`updated_by\` int NULL, \`deleted_by\` int NULL, UNIQUE INDEX \`IDX_64459517a9c0516dcfeb70fa7f\` (\`client_request_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_personal_info\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`father_name\` varchar(255) NULL, \`mother_name\` varchar(255) NULL, \`marital_status\` varchar(255) NULL, \`present_address\` text NULL, \`permanent_address\` text NULL, \`profession\` varchar(255) NULL, \`nominee_name\` varchar(255) NULL, \`relation_with_nominee\` varchar(255) NULL, \`comments\` text NULL, \`created_by\` int NULL, \`updated_by\` int NULL, \`deleted_by\` int NULL, \`user_id\` int NOT NULL, \`nid_photo_id\` int NULL, \`nominee_nid_photo_id\` int NULL, \`refer_user_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`folder\` ADD CONSTRAINT \`FK_afa55bd45385d7731c51de3eba3\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`folder\` ADD CONSTRAINT \`FK_ae991a4ac1bad2af0c06be6c560\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`folder\` ADD CONSTRAINT \`FK_82a84faa50e26fca20759bb3c24\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`folder\` ADD CONSTRAINT \`FK_c8f35e974e5c5f45d8803a72961\` FOREIGN KEY (\`company_id\`) REFERENCES \`company\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`gallery\` ADD CONSTRAINT \`FK_0f74efc873fee52182bb4901e54\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`gallery\` ADD CONSTRAINT \`FK_73247f9d2e296742ae2e1b86980\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`gallery\` ADD CONSTRAINT \`FK_2254620b97af3786723cd5a8162\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`gallery\` ADD CONSTRAINT \`FK_6048ebaa4100a5d6d874468602d\` FOREIGN KEY (\`folder_id\`) REFERENCES \`folder\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`gallery\` ADD CONSTRAINT \`FK_980765d8c55a26376160a21d014\` FOREIGN KEY (\`company_id\`) REFERENCES \`company\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_action\` ADD CONSTRAINT \`FK_35a27e861035e06f9b61d7a4d62\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_action\` ADD CONSTRAINT \`FK_f2b0ba1d72861fd9a02af3d96d2\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_action\` ADD CONSTRAINT \`FK_4e6b4180589bf1e10f8e436f3f5\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_action\` ADD CONSTRAINT \`FK_db06d82a57d7c9fb7dd36f5a631\` FOREIGN KEY (\`action_id\`) REFERENCES \`action\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_action\` ADD CONSTRAINT \`FK_f39cfd766e4b1a93e105c2fd675\` FOREIGN KEY (\`role_id\`) REFERENCES \`role\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`action\` ADD CONSTRAINT \`FK_513f1e020ad5ceafb38243fcc99\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`action\` ADD CONSTRAINT \`FK_fb357193ebb00db91b6c661e466\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`action\` ADD CONSTRAINT \`FK_d82f3c20a5a0ffd620f54e52d89\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`action\` ADD CONSTRAINT \`FK_6ffa6956165e8a372a397036544\` FOREIGN KEY (\`menu_id\`) REFERENCES \`menu\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_action\` ADD CONSTRAINT \`FK_2f2800a926203df078ed99618ee\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_action\` ADD CONSTRAINT \`FK_bdec1f05527c3a86a3a33cdaf45\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_action\` ADD CONSTRAINT \`FK_b37e2072f24b5246c50fb883a8f\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_action\` ADD CONSTRAINT \`FK_a3297a84ad4aba5b83152ac4273\` FOREIGN KEY (\`action_id\`) REFERENCES \`action\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_action\` ADD CONSTRAINT \`FK_baabb9b6ff427e792ad1f8558b1\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_action\` ADD CONSTRAINT \`FK_7ede2be2b24dab268facb817b80\` FOREIGN KEY (\`company_branch_id\`) REFERENCES \`company_branch\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_role\` ADD CONSTRAINT \`FK_0d65d1750949a41a47c174ed36a\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_role\` ADD CONSTRAINT \`FK_601092acc2e4c5bf3beb59de552\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_role\` ADD CONSTRAINT \`FK_d86c34a7d3f4de13a376d859b1f\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_role\` ADD CONSTRAINT \`FK_32a6fc2fcb019d8e3a8ace0f55f\` FOREIGN KEY (\`role_id\`) REFERENCES \`role\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_role\` ADD CONSTRAINT \`FK_d0e5815877f7395a198a4cb0a46\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_role\` ADD CONSTRAINT \`FK_307a6ac576ea8f1b98e71ca39f0\` FOREIGN KEY (\`company_branch_id\`) REFERENCES \`company_branch\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_company\` ADD CONSTRAINT \`FK_74c508bcbd01b6ce453a23527b7\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_company\` ADD CONSTRAINT \`FK_4bf177d648a0b1ef37ea03b4d91\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_company\` ADD CONSTRAINT \`FK_7bc5e3f600eaacbda8b351fd30f\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_company\` ADD CONSTRAINT \`FK_a34b2349be9db8ab53fe3d0e230\` FOREIGN KEY (\`company_id\`) REFERENCES \`company\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_company\` ADD CONSTRAINT \`FK_128160a3dfe4065da308a3cc6b3\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_company_branch\` ADD CONSTRAINT \`FK_e5d88a5a623ce236192071251b1\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_company_branch\` ADD CONSTRAINT \`FK_a4063959628df09c010898396ad\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_company_branch\` ADD CONSTRAINT \`FK_a2f15f853357d48be3e0b2abbf9\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_company_branch\` ADD CONSTRAINT \`FK_a0f4edf6f4c91b9ad8f1928c4d9\` FOREIGN KEY (\`company_id\`) REFERENCES \`company\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_company_branch\` ADD CONSTRAINT \`FK_12d9f19e418408bcb0756a19df2\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_company_branch\` ADD CONSTRAINT \`FK_b0a733a575b516b191454f54a0b\` FOREIGN KEY (\`company_branch_id\`) REFERENCES \`company_branch\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD CONSTRAINT \`FK_e4238c3828bc51ff8ca27c46385\` FOREIGN KEY (\`profile_picture_id\`) REFERENCES \`gallery\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_menu\` ADD CONSTRAINT \`FK_711340d011c34d1e3681b7b7246\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_menu\` ADD CONSTRAINT \`FK_0ce306fa523198d3a21893be3dc\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_menu\` ADD CONSTRAINT \`FK_19c71475c41bef04813e155f4dc\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_menu\` ADD CONSTRAINT \`FK_c22cdf874bcc1756774e746cf21\` FOREIGN KEY (\`menu_id\`) REFERENCES \`menu\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_menu\` ADD CONSTRAINT \`FK_2b894f35bf611630a8f5de5b40e\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_menu\` ADD CONSTRAINT \`FK_97ddec7afd04adaa1417899121a\` FOREIGN KEY (\`company_branch_id\`) REFERENCES \`company_branch\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`menu\` ADD CONSTRAINT \`FK_592f239d67fb01e3db306325de5\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`menu\` ADD CONSTRAINT \`FK_07c2fb7633405194486e0ffc1ac\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`menu\` ADD CONSTRAINT \`FK_3480ccb9d92107de249e8e687d3\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`menu\` ADD CONSTRAINT \`FK_e5e28130fd17f88ab5ee5d3aa4c\` FOREIGN KEY (\`parent_id\`) REFERENCES \`menu\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_menu\` ADD CONSTRAINT \`FK_0d50a43e3f8b59beee01da60426\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_menu\` ADD CONSTRAINT \`FK_d603d1aed76afe4f977f84e490e\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_menu\` ADD CONSTRAINT \`FK_67d83c6982183a7ab4edad562eb\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_menu\` ADD CONSTRAINT \`FK_96d26921e6aa2172256a55a6bc7\` FOREIGN KEY (\`menu_id\`) REFERENCES \`menu\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_menu\` ADD CONSTRAINT \`FK_25f45e543fbda0c91da4af7a2a9\` FOREIGN KEY (\`role_id\`) REFERENCES \`role\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role\` ADD CONSTRAINT \`FK_04a09925beea59e864e921db4a1\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role\` ADD CONSTRAINT \`FK_858c871a036f61e56e2740c7cda\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role\` ADD CONSTRAINT \`FK_7b5b6fdd043b90e1d461b4b681d\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role\` ADD CONSTRAINT \`FK_6c1faaaceb897cf61c5c91dcebf\` FOREIGN KEY (\`company_id\`) REFERENCES \`company\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company\` ADD CONSTRAINT \`FK_02d6084f6eb9912c0d8a35f9d0d\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company\` ADD CONSTRAINT \`FK_b8fdf420e133fe881a11a5f7068\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company\` ADD CONSTRAINT \`FK_c517fca3c837ddaa037f49ae8bd\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company\` ADD CONSTRAINT \`FK_6ab2cb6d2e7bbc45e236dfffc40\` FOREIGN KEY (\`image_id\`) REFERENCES \`gallery\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_branch\` ADD CONSTRAINT \`FK_7eb4dd832761b19785a2153f170\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_branch\` ADD CONSTRAINT \`FK_5435382364873b1a2f45029b2f1\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_branch\` ADD CONSTRAINT \`FK_d12181e63f49ee1c4f74bdf789e\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_branch\` ADD CONSTRAINT \`FK_e332ac44f8a1be64e931a5799da\` FOREIGN KEY (\`image_id\`) REFERENCES \`gallery\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_branch\` ADD CONSTRAINT \`FK_f462bb62b8fd8fae990a35b058c\` FOREIGN KEY (\`parent_id\`) REFERENCES \`company_branch\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_branch\` ADD CONSTRAINT \`FK_4698e0fa4704d223dba496ba05e\` FOREIGN KEY (\`company_id\`) REFERENCES \`company\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`otp_validation\` ADD CONSTRAINT \`FK_c4481f02e27bd69089089d34ef7\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`otp_validation\` ADD CONSTRAINT \`FK_edfa210813fa9a16cfb2164584d\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`otp_validation\` ADD CONSTRAINT \`FK_d94f16071e43d84299dea42720c\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` ADD CONSTRAINT \`FK_caa41b91f3c30a0f0a172187d9d\` FOREIGN KEY (\`created_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` ADD CONSTRAINT \`FK_331edc6c04733098c74e3b39f81\` FOREIGN KEY (\`updated_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` ADD CONSTRAINT \`FK_316d2ef1146129a4d233863f823\` FOREIGN KEY (\`deleted_by\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` ADD CONSTRAINT \`FK_26f4189498c6b038bfc624953c2\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` ADD CONSTRAINT \`FK_d39fdb10b9b1371666605df2a35\` FOREIGN KEY (\`nid_photo_id\`) REFERENCES \`gallery\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` ADD CONSTRAINT \`FK_961f12b246483a48d837dbbd557\` FOREIGN KEY (\`nominee_nid_photo_id\`) REFERENCES \`gallery\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` ADD CONSTRAINT \`FK_a23f383a4aaf0f6ec1c3ff64fe8\` FOREIGN KEY (\`refer_user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` DROP FOREIGN KEY \`FK_a23f383a4aaf0f6ec1c3ff64fe8\``);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` DROP FOREIGN KEY \`FK_961f12b246483a48d837dbbd557\``);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` DROP FOREIGN KEY \`FK_d39fdb10b9b1371666605df2a35\``);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` DROP FOREIGN KEY \`FK_26f4189498c6b038bfc624953c2\``);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` DROP FOREIGN KEY \`FK_316d2ef1146129a4d233863f823\``);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` DROP FOREIGN KEY \`FK_331edc6c04733098c74e3b39f81\``);
        await queryRunner.query(`ALTER TABLE \`user_personal_info\` DROP FOREIGN KEY \`FK_caa41b91f3c30a0f0a172187d9d\``);
        await queryRunner.query(`ALTER TABLE \`otp_validation\` DROP FOREIGN KEY \`FK_d94f16071e43d84299dea42720c\``);
        await queryRunner.query(`ALTER TABLE \`otp_validation\` DROP FOREIGN KEY \`FK_edfa210813fa9a16cfb2164584d\``);
        await queryRunner.query(`ALTER TABLE \`otp_validation\` DROP FOREIGN KEY \`FK_c4481f02e27bd69089089d34ef7\``);
        await queryRunner.query(`ALTER TABLE \`company_branch\` DROP FOREIGN KEY \`FK_4698e0fa4704d223dba496ba05e\``);
        await queryRunner.query(`ALTER TABLE \`company_branch\` DROP FOREIGN KEY \`FK_f462bb62b8fd8fae990a35b058c\``);
        await queryRunner.query(`ALTER TABLE \`company_branch\` DROP FOREIGN KEY \`FK_e332ac44f8a1be64e931a5799da\``);
        await queryRunner.query(`ALTER TABLE \`company_branch\` DROP FOREIGN KEY \`FK_d12181e63f49ee1c4f74bdf789e\``);
        await queryRunner.query(`ALTER TABLE \`company_branch\` DROP FOREIGN KEY \`FK_5435382364873b1a2f45029b2f1\``);
        await queryRunner.query(`ALTER TABLE \`company_branch\` DROP FOREIGN KEY \`FK_7eb4dd832761b19785a2153f170\``);
        await queryRunner.query(`ALTER TABLE \`company\` DROP FOREIGN KEY \`FK_6ab2cb6d2e7bbc45e236dfffc40\``);
        await queryRunner.query(`ALTER TABLE \`company\` DROP FOREIGN KEY \`FK_c517fca3c837ddaa037f49ae8bd\``);
        await queryRunner.query(`ALTER TABLE \`company\` DROP FOREIGN KEY \`FK_b8fdf420e133fe881a11a5f7068\``);
        await queryRunner.query(`ALTER TABLE \`company\` DROP FOREIGN KEY \`FK_02d6084f6eb9912c0d8a35f9d0d\``);
        await queryRunner.query(`ALTER TABLE \`role\` DROP FOREIGN KEY \`FK_6c1faaaceb897cf61c5c91dcebf\``);
        await queryRunner.query(`ALTER TABLE \`role\` DROP FOREIGN KEY \`FK_7b5b6fdd043b90e1d461b4b681d\``);
        await queryRunner.query(`ALTER TABLE \`role\` DROP FOREIGN KEY \`FK_858c871a036f61e56e2740c7cda\``);
        await queryRunner.query(`ALTER TABLE \`role\` DROP FOREIGN KEY \`FK_04a09925beea59e864e921db4a1\``);
        await queryRunner.query(`ALTER TABLE \`role_menu\` DROP FOREIGN KEY \`FK_25f45e543fbda0c91da4af7a2a9\``);
        await queryRunner.query(`ALTER TABLE \`role_menu\` DROP FOREIGN KEY \`FK_96d26921e6aa2172256a55a6bc7\``);
        await queryRunner.query(`ALTER TABLE \`role_menu\` DROP FOREIGN KEY \`FK_67d83c6982183a7ab4edad562eb\``);
        await queryRunner.query(`ALTER TABLE \`role_menu\` DROP FOREIGN KEY \`FK_d603d1aed76afe4f977f84e490e\``);
        await queryRunner.query(`ALTER TABLE \`role_menu\` DROP FOREIGN KEY \`FK_0d50a43e3f8b59beee01da60426\``);
        await queryRunner.query(`ALTER TABLE \`menu\` DROP FOREIGN KEY \`FK_e5e28130fd17f88ab5ee5d3aa4c\``);
        await queryRunner.query(`ALTER TABLE \`menu\` DROP FOREIGN KEY \`FK_3480ccb9d92107de249e8e687d3\``);
        await queryRunner.query(`ALTER TABLE \`menu\` DROP FOREIGN KEY \`FK_07c2fb7633405194486e0ffc1ac\``);
        await queryRunner.query(`ALTER TABLE \`menu\` DROP FOREIGN KEY \`FK_592f239d67fb01e3db306325de5\``);
        await queryRunner.query(`ALTER TABLE \`user_menu\` DROP FOREIGN KEY \`FK_97ddec7afd04adaa1417899121a\``);
        await queryRunner.query(`ALTER TABLE \`user_menu\` DROP FOREIGN KEY \`FK_2b894f35bf611630a8f5de5b40e\``);
        await queryRunner.query(`ALTER TABLE \`user_menu\` DROP FOREIGN KEY \`FK_c22cdf874bcc1756774e746cf21\``);
        await queryRunner.query(`ALTER TABLE \`user_menu\` DROP FOREIGN KEY \`FK_19c71475c41bef04813e155f4dc\``);
        await queryRunner.query(`ALTER TABLE \`user_menu\` DROP FOREIGN KEY \`FK_0ce306fa523198d3a21893be3dc\``);
        await queryRunner.query(`ALTER TABLE \`user_menu\` DROP FOREIGN KEY \`FK_711340d011c34d1e3681b7b7246\``);
        await queryRunner.query(`ALTER TABLE \`user\` DROP FOREIGN KEY \`FK_e4238c3828bc51ff8ca27c46385\``);
        await queryRunner.query(`ALTER TABLE \`user_company_branch\` DROP FOREIGN KEY \`FK_b0a733a575b516b191454f54a0b\``);
        await queryRunner.query(`ALTER TABLE \`user_company_branch\` DROP FOREIGN KEY \`FK_12d9f19e418408bcb0756a19df2\``);
        await queryRunner.query(`ALTER TABLE \`user_company_branch\` DROP FOREIGN KEY \`FK_a0f4edf6f4c91b9ad8f1928c4d9\``);
        await queryRunner.query(`ALTER TABLE \`user_company_branch\` DROP FOREIGN KEY \`FK_a2f15f853357d48be3e0b2abbf9\``);
        await queryRunner.query(`ALTER TABLE \`user_company_branch\` DROP FOREIGN KEY \`FK_a4063959628df09c010898396ad\``);
        await queryRunner.query(`ALTER TABLE \`user_company_branch\` DROP FOREIGN KEY \`FK_e5d88a5a623ce236192071251b1\``);
        await queryRunner.query(`ALTER TABLE \`user_company\` DROP FOREIGN KEY \`FK_128160a3dfe4065da308a3cc6b3\``);
        await queryRunner.query(`ALTER TABLE \`user_company\` DROP FOREIGN KEY \`FK_a34b2349be9db8ab53fe3d0e230\``);
        await queryRunner.query(`ALTER TABLE \`user_company\` DROP FOREIGN KEY \`FK_7bc5e3f600eaacbda8b351fd30f\``);
        await queryRunner.query(`ALTER TABLE \`user_company\` DROP FOREIGN KEY \`FK_4bf177d648a0b1ef37ea03b4d91\``);
        await queryRunner.query(`ALTER TABLE \`user_company\` DROP FOREIGN KEY \`FK_74c508bcbd01b6ce453a23527b7\``);
        await queryRunner.query(`ALTER TABLE \`user_role\` DROP FOREIGN KEY \`FK_307a6ac576ea8f1b98e71ca39f0\``);
        await queryRunner.query(`ALTER TABLE \`user_role\` DROP FOREIGN KEY \`FK_d0e5815877f7395a198a4cb0a46\``);
        await queryRunner.query(`ALTER TABLE \`user_role\` DROP FOREIGN KEY \`FK_32a6fc2fcb019d8e3a8ace0f55f\``);
        await queryRunner.query(`ALTER TABLE \`user_role\` DROP FOREIGN KEY \`FK_d86c34a7d3f4de13a376d859b1f\``);
        await queryRunner.query(`ALTER TABLE \`user_role\` DROP FOREIGN KEY \`FK_601092acc2e4c5bf3beb59de552\``);
        await queryRunner.query(`ALTER TABLE \`user_role\` DROP FOREIGN KEY \`FK_0d65d1750949a41a47c174ed36a\``);
        await queryRunner.query(`ALTER TABLE \`user_action\` DROP FOREIGN KEY \`FK_7ede2be2b24dab268facb817b80\``);
        await queryRunner.query(`ALTER TABLE \`user_action\` DROP FOREIGN KEY \`FK_baabb9b6ff427e792ad1f8558b1\``);
        await queryRunner.query(`ALTER TABLE \`user_action\` DROP FOREIGN KEY \`FK_a3297a84ad4aba5b83152ac4273\``);
        await queryRunner.query(`ALTER TABLE \`user_action\` DROP FOREIGN KEY \`FK_b37e2072f24b5246c50fb883a8f\``);
        await queryRunner.query(`ALTER TABLE \`user_action\` DROP FOREIGN KEY \`FK_bdec1f05527c3a86a3a33cdaf45\``);
        await queryRunner.query(`ALTER TABLE \`user_action\` DROP FOREIGN KEY \`FK_2f2800a926203df078ed99618ee\``);
        await queryRunner.query(`ALTER TABLE \`action\` DROP FOREIGN KEY \`FK_6ffa6956165e8a372a397036544\``);
        await queryRunner.query(`ALTER TABLE \`action\` DROP FOREIGN KEY \`FK_d82f3c20a5a0ffd620f54e52d89\``);
        await queryRunner.query(`ALTER TABLE \`action\` DROP FOREIGN KEY \`FK_fb357193ebb00db91b6c661e466\``);
        await queryRunner.query(`ALTER TABLE \`action\` DROP FOREIGN KEY \`FK_513f1e020ad5ceafb38243fcc99\``);
        await queryRunner.query(`ALTER TABLE \`role_action\` DROP FOREIGN KEY \`FK_f39cfd766e4b1a93e105c2fd675\``);
        await queryRunner.query(`ALTER TABLE \`role_action\` DROP FOREIGN KEY \`FK_db06d82a57d7c9fb7dd36f5a631\``);
        await queryRunner.query(`ALTER TABLE \`role_action\` DROP FOREIGN KEY \`FK_4e6b4180589bf1e10f8e436f3f5\``);
        await queryRunner.query(`ALTER TABLE \`role_action\` DROP FOREIGN KEY \`FK_f2b0ba1d72861fd9a02af3d96d2\``);
        await queryRunner.query(`ALTER TABLE \`role_action\` DROP FOREIGN KEY \`FK_35a27e861035e06f9b61d7a4d62\``);
        await queryRunner.query(`ALTER TABLE \`gallery\` DROP FOREIGN KEY \`FK_980765d8c55a26376160a21d014\``);
        await queryRunner.query(`ALTER TABLE \`gallery\` DROP FOREIGN KEY \`FK_6048ebaa4100a5d6d874468602d\``);
        await queryRunner.query(`ALTER TABLE \`gallery\` DROP FOREIGN KEY \`FK_2254620b97af3786723cd5a8162\``);
        await queryRunner.query(`ALTER TABLE \`gallery\` DROP FOREIGN KEY \`FK_73247f9d2e296742ae2e1b86980\``);
        await queryRunner.query(`ALTER TABLE \`gallery\` DROP FOREIGN KEY \`FK_0f74efc873fee52182bb4901e54\``);
        await queryRunner.query(`ALTER TABLE \`folder\` DROP FOREIGN KEY \`FK_c8f35e974e5c5f45d8803a72961\``);
        await queryRunner.query(`ALTER TABLE \`folder\` DROP FOREIGN KEY \`FK_82a84faa50e26fca20759bb3c24\``);
        await queryRunner.query(`ALTER TABLE \`folder\` DROP FOREIGN KEY \`FK_ae991a4ac1bad2af0c06be6c560\``);
        await queryRunner.query(`ALTER TABLE \`folder\` DROP FOREIGN KEY \`FK_afa55bd45385d7731c51de3eba3\``);
        await queryRunner.query(`DROP TABLE \`user_personal_info\``);
        await queryRunner.query(`DROP INDEX \`IDX_64459517a9c0516dcfeb70fa7f\` ON \`otp_validation\``);
        await queryRunner.query(`DROP TABLE \`otp_validation\``);
        await queryRunner.query(`DROP INDEX \`IDX_6bcfe5fa6ded76d85ca7f8ff08\` ON \`company_branch\``);
        await queryRunner.query(`DROP TABLE \`company_branch\``);
        await queryRunner.query(`DROP INDEX \`IDX_47216baa0f0c8ebc6ee5a74989\` ON \`company\``);
        await queryRunner.query(`DROP INDEX \`IDX_a76c5cd486f7779bd9c319afd2\` ON \`company\``);
        await queryRunner.query(`DROP TABLE \`company\``);
        await queryRunner.query(`DROP INDEX \`IDX_ae4578dcaed5adff96595e6166\` ON \`role\``);
        await queryRunner.query(`DROP TABLE \`role\``);
        await queryRunner.query(`DROP TABLE \`role_menu\``);
        await queryRunner.query(`DROP INDEX \`IDX_f37c203e9d061c884c4b034c83\` ON \`menu\``);
        await queryRunner.query(`DROP TABLE \`menu\``);
        await queryRunner.query(`DROP TABLE \`user_menu\``);
        await queryRunner.query(`DROP INDEX \`IDX_e12875dfb3b1d92d7d7c5377e2\` ON \`user\``);
        await queryRunner.query(`DROP TABLE \`user\``);
        await queryRunner.query(`DROP TABLE \`user_company_branch\``);
        await queryRunner.query(`DROP TABLE \`user_company\``);
        await queryRunner.query(`DROP TABLE \`user_role\``);
        await queryRunner.query(`DROP TABLE \`user_action\``);
        await queryRunner.query(`DROP INDEX \`IDX_a37ba4bbcb187af36aa07b86c7\` ON \`action\``);
        await queryRunner.query(`DROP INDEX \`IDX_4aa35beeebe7073b51be93aae6\` ON \`action\``);
        await queryRunner.query(`DROP TABLE \`action\``);
        await queryRunner.query(`DROP TABLE \`role_action\``);
        await queryRunner.query(`DROP INDEX \`IDX_295fd6b6065fd46b418d79c6d0\` ON \`gallery\``);
        await queryRunner.query(`DROP TABLE \`gallery\``);
        await queryRunner.query(`DROP TABLE \`folder\``);
    }

}
